### ISSUE TITLE
F2P games are corrupted when installing with DBI

### ISSUE THREAD

**Issue by FlyingBananaTree** [rashevskyv/dbi#1]
F2P games are corrupted when installing with DBI. For example Warframe, or Rocket League's latest update (v2555904)

- DBI will show 0% installation progress until it's finished but for example with dbibackend you can see the data is being sent
- When installation is complete you will see a hash mismatch error for one of the ncas even if the original file is not corrupt
- The game will not boot after installing

How to reproduce:

- Install any F2P (free to play) game or update, I suggest Rocket League update v2555904 as Rocket League was recently changed into a free to play game

**Comment by rashevskyv** [comment]
It is very like to nscb decriptor issue. If you unpack NSZ of this updates and pack them via nsz from nicoboss, all will be fine. 
DBI dev try hard to fix this issue on DBI's side, but no success for now

**Comment by rashevskyv** [comment]
https://github.com/rashevskyv/dbi/releases/tag/181

Please try this version and give me feedback

**Comment by FlyingBananaTree** [comment]
The result was exactly the same as before unfortunately.

Tested Rocket League update v2555904 - nsz file compressed with NSCB level 22 0 threads

**Comment by rashevskyv** [comment]
> 
> 
> The result was exactly the same as before unfortunately.
> 
> Tested Rocket League update v2555904 - nsz file compressed with NSCB level 22 0 threads

https://github.com/rashevskyv/dbi/releases/tag/184

Try this one. No chances if files converted by latest NSCB will be work correctly, but may be DBI will not freeze

**Comment by FlyingBananaTree** [comment]
Again tested Rocket League update v2555904 - nsz file compressed with NSCB level 22 0 threads. 

The issue seems to be fixed! DBI progress works properly, the file installed correctly and the game works.
