### ISSUE TITLE
The ‘Cleanup orphaned files` feature make some XCI to fail to work.

### ISSUE THREAD

**Issue by ZUIcat** [rashevskyv/dbi#10]
DBI：Version 197
SXOS：3.05

When I use the `Cleanup orphaned files` feature. It removes some files about _Zelda_ and _Xenoblade 1_, and then their XCI doesn't work. Later, I fixed _Xenoblade 1_ by plugging in my _Xenoblade 1_ game card (this seems to have installed some tickets). I found this feature updated in version 200, but I don't know if you fixed it. (Sorry, I'm afraid to try this feature. I sold my _Zelda_ game card, so I couldn't fix _Zelda_. I'm recreating the EmuNAND now...)

**Comment by rashevskyv** [comment]
"I have no idea what happens on SXOS when mounting CXCI with updates (and there they obviously used such). This case is clearly undocumented. Moreover, I do not know why re-mounting after cleanup does not return what was added to the system after the first mount and was cleaned up. In my opinion, this is a bug in image mounting."
