### ISSUE TITLE
usb3.0

### ISSUE THREAD

**Issue by lsp199308** [rashevskyv/dbi#100]
Since hos13.0.0, usb3.0 is not available, but nca can be patched to use usb3.0, patched as follows
PATCH magic：50  41  54  43  48
Offset： 00  76  34
Size of patch：00  08
Patch to be applied：20  00  80  52  C0  03  5F  D6  
EOF magic： 45  4F  46

Sadly the dbi is not working, I I tried awoo and it enabled usb3.0, the dbi is perfect, I think you can fix it, thanks

**Comment by FlyingBananaTree** [comment]
There's no need for manual patching, 13.0.0+ patches _were_ missing from atmosphere until 1.2.5 released but USB patches for up to 14.1.1 are now present:
https://github.com/Atmosphere-NX/Atmosphere/blob/master/stratosphere/loader/source/ldr_embedded_usb_patches.inc#L53

Activate USB 3.0 in atmosphere's `system_settings.ini` as the DBI readme explains.

**Comment by lsp199308** [comment]
Thanks for your reply, I activated usb3.0 but dbi still only has 30m/s install speed, in hos12.0.0 dbi has 70m/s install speed, I always use DBI, it's very cool installer, but as I understand Nintendo added something in hos13.0.0 that might be 4k video, which will take priority over usb3.0, so I did try to manually patch usb3.0 so that it always enables usb3.0, I did many attempts, awoo, tinwoo, tleaf, they install nsp at 80m/s, but dbi is always only 30m/s, maybe I missed something, I will double check, I tried to recompile the atmosphere loader. kip, which still didn't work.
https://github.com/lsp199308/Atmosphere/blob/usb3.0/stratosphere/loader/source/ldr_embedded_usb_patches.inc

I am not a premium user, sorry, please excuse my English, it is not my native language

**Comment by Masamune3210** [comment]
I am not sure where you got that 13.0.0 added anything to do with 4K, I'm not seeing it anywhere and would imagine if that was true that there would be people talking about it everywhere by now since the firmware came out in Oct of last year

**Comment by lsp199308** [comment]
https://switchbrew.org/wiki/System_Settings#usb
They first came from SciresM's Twitter feed

**Comment by lsp199308** [comment]
Oh my god, I misunderstood, but in the firmware with title 01000000000000000006, it needs to be patched to use usb3.0, I have been using usb3.0 to install games since dbi supported usb3.0, hos13.0.0 onwards, they are not working, I have no programming related skills, so, I don't quite understand, maybe I am wrong I'm sorry, please forgive me

**Comment by lsp199308** [comment]
![image](https://user-images.githubusercontent.com/77911322/166128605-698b4dcc-9277-4091-98da-8c71f2a621ad.jpeg)

This is the installation speed of awoo after fixing nca, I think that dbi should be able to make usb3.0 work, I am sorry I will close this issue because I am not an advanced user
