### ISSUE TITLE
no parse content meta found

### ISSUE THREAD

**Issue by DiegoChairs** [rashevskyv/dbi#102]
hows goin, im havin a issue with dbi installer using Run MTP responder, first i download a game and put it on the microsd install and when it just goin to finish it crashes with the path of "no parse content meta found, installation aborted" what can i do? thanks

**Comment by duckbill007** [comment]
Not enough info. What is your cfw ofw and DBI versions?

**Comment by DiegoChairs** [comment]
I Was on 258 version so, i just upgrade dbi and that it fixes my issue
thanks for Your Work bro
