### ISSUE TITLE
Latest dbibackend.exe is stuck in a infinite "loop"

### ISSUE THREAD

**Issue by WhitePower69** [rashevskyv/dbi#105]
Only thing that fixed it was the 358 version of dbibackend.exe, the new version of dbibackend.exe doesn't work.

**Comment by rashevskyv** [comment]
Dbibackend are the same. It wasnt apdated for long time. But i will check

нд, 29 трав. 2022, 22:12 користувач WhitePower69 ***@***.***>
пише:

**Comment by WhitePower69** [comment]
Can't be the same though, the new dbibackend.exe is 7.37 MBs, while the 358 version is 9.1 MBs. So there's that.

**Comment by rashevskyv** [comment]
Thank you for noticing. Tommorow will change it back. Idk how its happens 🤔😅

**Comment by rashevskyv** [comment]
Fixed
