### ISSUE TITLE
New feauture to check games updates from external database not explained on the readme

### ISSUE THREAD

**Issue by jonasmare** [rashevskyv/dbi#106]
I did not find anything on the README regarding how the recent ability to ''check games updates from external database'' added on the latest release of DBI works. This are the questions I have:

1. Is the 'external database' used, this file from here https://github.com/blawar/titledb/blob/master/versions.txt or is there any other databases supported?
2. Does DBI already comes with the 'external database' or do we need to connect the Switch to the internet in order for DBI to grab or update the necessary files?
3. Assuming that DBI grabs or updates the database by connecting to the internet, and since blawar's titledb is updated quite often (daily), is there a way to manually update the database without connecting the Switch to the internet (some people prefer to keep their Switch offline), by dragging the versions.txt? file into the right place at the SD card (which place that would be?), preferably via USB MTP or dbibackend?

**Comment by jonasmare** [comment]
If I understood right, when the Switch is always offline, I just need to open dbi.config on my computer (I assume you can't do this on the Switch itself) with something like notepad and edit the following:

```
; URL with title versions in format <id>|<rightsId>|[version]
VersionsURL=https://raw.githubusercontent.com/blawar/titledb/master/versions.txt
; VersionsURL=sdmc:/versions.txt
```

to

```
; URL with title versions in format <id>|<rightsId>|[version]
; VersionsURL=https://raw.githubusercontent.com/blawar/titledb/master/versions.txt
VersionsURL=sdmc:/versions.txt
```

After that, just move the edited dbi.config into the switch and manually grab https://github.com/blawar/titledb/blob/master/versions.txt and put it on sdmc:/versions.txt and from there on I can just use USB MTP to replace the versions.txt file to a more recent one.
I also assume DBI will need to be restart every time I update the versions.txt via USB MTP in order for it to pick up the new file or restart is not needed?

**Comment by jonasmare** [comment]
Thx for the clarification.
Feel free to close this thread or leave it open if you wish to be reminded to update the README or something.

**Comment by rashevskyv** [comment]
Readme updated
