### ISSUE TITLE
Xcz with multiple files (base / dlc / updates) crash during installation

### ISSUE THREAD

**Issue by ginkuji** [rashevskyv/dbi#11]
Hi again! im using the latest build dbi 201
Atmos 15
Also tested on sx os 3.1
Firmware 10.2
Tested on direct otg installation from external hardrive.

Dbi crashes during the initial installation of xcz files. I hope this feature will be added in future updates.

**Comment by HY-Leung** [comment]
The NSCB also fail with ncz in nsz files

**Comment by rashevskyv** [comment]
Please try DBI 204

**Comment by FlyingBananaTree** [comment]
> 
> Dbi crashes during the initial installation of xcz files. I hope this feature will be added in future updates.

DBI doesn't support xcz files. 1. nsp or nsz over MTP 2. nsp, xci or nsz over USB/SD/network
