### ISSUE TITLE
Feature - Ability to install Updates/DLCs, not just check

### ISSUE THREAD

**Issue by Viper911** [rashevskyv/dbi#114]
I see the option to check for title updates, but all it seems to do is report what it found.  This screen should allow you to apply the updates/DLCs it found either one by one or select all and apply.  Right now it seems the only way to do this is go to the install screen and find them one by one to apply them, hoping you remember the list of 50 it had found.

**Comment by duckbill007** [comment]
Когда ты на экране, откуда можно ставить, все апдейты и так подсвечены. Кроме того, есть действие по выбору всех апдейтов в списке.
