### ISSUE TITLE
DBI 386 lost a feature to dump installed titles

### ISSUE THREAD

**Issue by sthetix** [rashevskyv/dbi#116]
as the title says, DBI 386 lost a feature to dump installed titles, I cannot see it inside the MTP responder mode.

Thanks

**Comment by rashevskyv** [comment]
Whats thats exactly means? Did you lost "installed titles" folder? If so,
check if it is enabled on config

пт, 29 лип. 2022, 09:42 користувач sthetix ***@***.***> пише:

**Comment by sthetix** [comment]
Thanks bro, you are the best. I didn't know that
you can close this issue

**Comment by duckbill007** [comment]
Прошу прощения. Не проверил эту строчку при сборке релиза. Во время дебага просто отключал этот сторадж для ускорения запуска.
