### ISSUE TITLE
Clean orphan files freezes console

### ISSUE THREAD

**Issue by josete2k** [rashevskyv/dbi#117]
DBI 389

Fresh emummc and when I clean orphan files DBI sais that are a lof of error reports... and system freezes or slowing...

**Comment by josete2k** [comment]
Update:

Tested applet mode a full ram mode.

Now it founds 8200 error reports and FAILED when cleaning.

**Comment by duckbill007** [comment]
Скажите спасибо атмосфере, которая загадила вам карту бессмысленными репортами.

**Comment by josete2k** [comment]
> Скажите спасибо атмосфере, которая загадила вам карту бессмысленными репортами.

Well it's an clean install and other versions are working fine

**Comment by josete2k** [comment]
![2022073023015800-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/561354/181996192-de9ab994-1623-4aaf-8c4c-8aea7258479c.jpg)

**Comment by josete2k** [comment]
![2022073023062100-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/561354/181996199-893bccb7-dde2-4bcc-a808-6e10b0e7ab35.jpg)

**Comment by josete2k** [comment]
![2022073023025600-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/561354/181996212-0161e676-b7f2-407a-9f78-1fdd841bc29f.jpg)

**Comment by josete2k** [comment]
The number of error reports changes:
![2022073023062100-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/561354/181996239-19f65f87-d95a-4c44-87bb-84c14cf2ff22.jpg)

**Comment by rashevskyv** [comment]
Cope data from your sd to pc, format sd to fat32 and put all data back, except logs folder.

Make clearning every few days or use kefir, where logging is disabled.
