### ISSUE TITLE
FTP is causing Horizon to freeze

### ISSUE THREAD

**Issue by BlackRabbit22** [rashevskyv/dbi#118]
- Atmosphere version: 
   - 1.3.2
- Firmware version:
  - 14.1.2
- No sysmodules are used.

- Device type:
  - Mariko
- PC OS used:
  - Windows

How to reproduce the issue:
1, Launch DBI through applet mode.
2. Run FTP.
3. Access FTP folder.
4. Exit application through B button or home button.
5. Launch DBI again, and run FTP again.
6. Access FTP location or a folder in the FTP location.
7. Exit out of DBI through home button.
8. Horizon freezes.

**Note:**
Horizon only unfreezes when trying to reconnect from the PC to the FTP server.
Issue also doesn't occur when launching via title override mode.

**Comment by duckbill007** [comment]
Самое главное где - какая версия DBI?

Под линуксом воспроизвести не получается.

**Comment by BlackRabbit22** [comment]
> Самое главное где - какая версия DBI?

DBI 389

> Под линуксом воспроизвести не получается.

I just tested it on Linux and the same issue occurs.

Would you like to me to provide my config?

**Comment by duckbill007** [comment]
В пункте 6 - листинг директории получается нормально?

**Comment by BlackRabbit22** [comment]
@duckbill007 yes, in point 6 when accessing the directory, the directory shows up fine.

The is when you exit the software a second time via the home menu button.

**Comment by duckbill007** [comment]
Никогда не выходите из хомбрю по кнопке Home.
