### ISSUE TITLE
dbi slow menu movement

### ISSUE THREAD

**Issue by lowburger** [rashevskyv/dbi#12]
Hi. I use dbi since very old version but with new version the menu cursor move very slowly after button press, can be fixed?

**Comment by ImanCol** [comment]
Launch HBL>DBI from a game by holding R

**Comment by lowburger** [comment]
> 
> 
> Launch HBL>DBI from a game by holding R

No this is issue on both modes.

**Comment by r1cola** [comment]
Yea, can noticed this too.  pretty minor, but still noticeable...not sure which build actually made the change...

**Comment by FlyingBananaTree** [comment]
> 
> 
> Yea, noticed this too. pretty minor, but still noticeable...not sure which build actually made the change...

The menu lag was introduced in DBI 197, I actually reported this before: https://github.com/rashevskyv/dbi/issues/9

**Comment by r1cola** [comment]
233 looks to have improved this issue

**Comment by lowburger** [comment]
> 233 looks to have improved this issue

No is totally the same...

**Comment by rashevskyv** [comment]
https://github.com/rashevskyv/dbi/releases/tag/251

**Comment by lowburger** [comment]
Now is great big thx!
