### ISSUE TITLE
IIS Home Server support

### ISSUE THREAD

**Issue by Flygsand** [rashevskyv/dbi#120]
When using  the `ApacheHTTP` home server type with IIS Directory Browsing, no games show up in DBI. I've included two raw responses from IIS for reproduction of the issue:

A listing containing directories only:
[dirs.txt](https://github.com/rashevskyv/dbi/files/9256019/dirs.txt)

A listing containing files only:
[files.txt](https://github.com/rashevskyv/dbi/files/9256020/files.txt)

**Comment by duckbill007** [comment]
Из приведённых листингов видно, что IIS использует абсолютные пути в листинге. DBI ожидает относительные. Такой тип листинга не поддерживается.
