### ISSUE TITLE
Cannot restore saves

### ISSUE THREAD

**Issue by zakwarrior** [rashevskyv/dbi#121]
Hi there,

I'm having issues with DBI, i made a backup of all my saves from my old switch a while ago

Today i got a new switch and i'm trying to restore these saves, but it doesn't work, i get an error: File xxxxxx can not be created (xxxxxx is the mane of the games)

here is a screenshot
![20220807_034545](https://user-images.githubusercontent.com/5190445/183271783-295af3f0-a2f7-404e-ae0b-d5b39ab6fd98.jpg)

I then after checked the DBI.config and foudn this 
; Browse saves FS in Read-only mode
ROSaveFS=true

So i changed it to false, result is the same, i get exactly the same error File xxxxxx can not be created 
I tried to deleate the line ROSaveFS=true, same thing i get the same error

For information i have a switch OLED, and I tried this with 2 different computers, get exatly same error

Thanks for the help and great job with your work on DBI ;)

**Comment by Masamune3210** [comment]
Have you opened the game at least once to make sure that it can make its save archive? I think DBI can do it on its own but its still worth a shot

**Comment by duckbill007** [comment]
Установлена ли сама игра? Пользователь называется так же? Куда именно и что копируется?

ROSaveFS не имеет отношения к mtp.

**Comment by zakwarrior** [comment]
Hello, no the games were not installed or launched...

After installing the game and loading it once, i can now restore my saves

I looked up this guide here: https://github.com/rashevskyv/dbi/blob/main/README_ENG.md#browse-saves

_Backup, restore and manage save data for both installed and uninstalled games. You can make a backup of them by copying them to a PC and also delete saves that you no longer want or need - to do this open the folder with the name of the game you need, then delete the required save folder. In order to restore saves, copy them to the appropriate folder from your PC. 
**DBI does not require pre-launching the game before restoring a save.**_

So i was thinking it was not necessary to launch the game first

sorry for wasting you time, and thanks for the help ;)

Regards

**Comment by lowburger** [comment]
Game must installed when restore, launch doesn't matter.
