### ISSUE TITLE
Document dbibackend Command Line Options?

### ISSUE THREAD

**Issue by mostanon** [rashevskyv/dbi#122]
The `dbibackend` script already accepts command line options, but because there is no `--help` command and it's not documented in the dbi/README.md, few people will discover the options.

Every file that is passed to `dbibackend` on the command line will be loaded into `dbibackend` and as long as one or more files are loaded, then `do_start_server()` will be run automatically.

Just run:

```
python ~/dbi/dbibackend ~/Switch/File1.nsp ~/Switch/File2.nsp ~/Switch/File3.nsp
```

And the additional files will be auto loaded into the dbibackend as if you had used the GUI to choose them, and the server will be started.

```
if len(sys.argv) < 2:
    start_gui(False)
else:
    for filename in sys.argv[1:]:
        d = Path(filename)
        if d.is_file():
            file_list.update({d.name: d.resolve()})
        else:
            for file_path in [f for f in d.iterdir() if f.is_file()]:
                file_list.update({file_path.name : file_path.resolve()})
    
    start_gui(True)
```

**Comment by duckbill007** [comment]
dbibackend - устаревший и неподдерживаемый способ

**Comment by mostanon** [comment]
Спасибо вам за вашу работу.
Могу я спросить, что нам теперь использовать вместо dbibackend?

Thank you for your work.
May I ask, what should we use now instead of dbibackend?

**Comment by duckbill007** [comment]
MTP

**Comment by rashevskyv** [comment]
Added to readme
