### ISSUE TITLE
dbi will be open source one day ?

### ISSUE THREAD

**Issue by PoloNX** [rashevskyv/dbi#123]
title

**Comment by duckbill007** [comment]
А почему вы спрашиваете? Что не устраивает?

**Comment by PoloNX** [comment]
open source is good for new developper who wants to learn

**Comment by duckbill007** [comment]
В мире достаточно опен сорса, чтобы учиться. Если нужно именно на свитч, можно читать исходники атмосферы до полного просветления.

**Comment by DraconicNEO** [comment]
> There is enough open source in the world to learn. If you need it on the switch, you can read the source code of the atmosphere until it is completely clear.



> В мире достаточно опен сорса, чтобы учиться. Если нужно именно на свитч, можно читать исходники атмосферы до полного просветления.

The primary reason for making things open source, especially in the switch scene is so that their development can be continued even if the original author goes inactive. In the case of DBI being closed source if the main dev and his collaborators (that's you) go inactive and an update to the Nintendo switch breaks the app nobody will be able to step in and fix it easily.

Open sourcing is not just about learning it's about longevity.

**Comment by duckbill007** [comment]
Не вижу в этом никакой проблемы. У DBI нет ни одной уникальной функции. Всё доступно в других, в том числе open source проектах.

**Comment by DraconicNEO** [comment]
> I don't see any problem with this. DBI does not have any unique features. Everything is available in others, including open source projects.

I don't think that there's one (that's open source) which has MTP support and still works on latest firmware. I guess there's no reason why other developers couldn't add this feature to their installers (I'm going to go convince a few of them to do that after writing this).

And then of course there's the second reason why things are open source which is for transparency purposes. I'm not going to go over this one too much but when devs in The Homebrew community don't open source there work it usually says two things.

1. They have something to hide that people won't like.
2. They don't want to contribute to the rest of the Homebrew community.

I'm not trying to accuse you of either of those things I'm just pointing this out in the case of other Homebrew developers who chose to go this route. 
Maybe you don't think it's necessary and it is your choice after all but an open source app would definitely be seen as more trustworthy by the community.

**Comment by duckbill007** [comment]
ОК. Напишу более понятными словами. DBI использует библиотеку, чья лицензия не допускает использование в open source проектах.

**Comment by duckbill007** [comment]
Что касается MTP:
Я правильно понимаю, что независмые одиночки уже трижды (nxmtp, tinfoil, dbi) смогли сделать то, что всё "Homebrew community" сообща так и не осилило? А всё что смогло (mtp-server-nx) - взять код, написанный Google для ядра Android, да и тот не смогли довести до работоспособного состояния.

**Comment by DraconicNEO** [comment]
> OK. I will write in clearer terms. DBI uses a library whose license does not allow use in open source projects.

That kind of makes sense, although that does seem a bit weird to me since I don't really know of any Switch Homebrew libraries that have such a license (other than the official Nintendo SDK).

**Comment by DraconicNEO** [comment]
> As for MTP: Do I understand correctly that independent loners already three times (nxmtp, tinfoil, dbi) were able to do what the entire "Homebrew community" together did not master? And all that could (mtp-server-nx) was to take the code written by Google for the Android kernel, and even that could not be brought to a workable state.

I think that's it, I'm not 100% sure why there are no decent open source solutions for MTP in the Switch Scene.

**Comment by duckbill007** [comment]
> That kind of makes sense, although that does seem a bit weird to me since I don't really know of any Switch Homebrew libraries that have such a license (other than the official Nintendo SDK).

Эта библиотека не имеет ничего общего с Switch Homebrew. Я говорю о библиотеке для GUI в консоли. Библиотека разрабатывается мной уже почти 30 лет и до сих пор успешно применяется во многих коммерческих проектах.

**Comment by DraconicNEO** [comment]
> > That kind of makes sense, although that does seem a bit weird to me since I don't really know of any Switch Homebrew libraries that have such a license (other than the official Nintendo SDK).
> 
> This library has nothing to do with Switch Homebrew. I'm talking about a GUI library in the console. The library has been developed by me for almost 30 years and is still successfully used in many commercial projects.

The MS-DOS style UI of the app? Is that what you're talking about?

**Comment by duckbill007** [comment]
> The MS-DOS style UI of the app? Is that what you're talking about?

Да. Именно оно.

**Comment by DraconicNEO** [comment]
> > The MS-DOS style UI of the app? Is that what you're talking about?
> 
> Yes. That's it.

I wonder if it will be possible to make parts of the app open source though, without any UI elements. 

Although I'm sure that would be a lot of work and might not even be possible.

**Comment by duckbill007** [comment]
Это потребует вычленения участков кода в отдельные процессы без линковки с ui кодом, что как я понимаю не поддерживается в homebrew ABI.
