### ISSUE TITLE
[REQUEST] Install Saves via MTP server

### ISSUE THREAD

**Issue by deejay87** [rashevskyv/dbi#124]
Hi, 

can you add possibility to install saves by folder/files via MTP server  (like MTP responder) ?

Thanks

**Comment by duckbill007** [comment]
Дважды перечитал. Ничего не понял. Всё и так есть.

**Comment by deejay87** [comment]
MTP server on port 6000 
"MicroSD install"
"NAND install"

My question is about the possibility to add : "Saves > Installed games" 
Cause people use the phone to install via ftp and this can be usefull if it's possible :)

**Comment by duckbill007** [comment]
Работа с сейвами по MTP реализована сто лет назад.
