### ISSUE TITLE
Code used to quit the app without returning to HBMenu

### ISSUE THREAD

**Issue by shadow2560** [rashevskyv/dbi#127]
Hi,

First I want to thank you for your great app, for me probably one of the best on the Switch's scene, your MTP mode is realy incredible and is a great support for me with my visual disability.

I have a question for you to help me to my code, how dif you do to exit your app and return directly to the home and even quit the app used to launch the Homebrew without applet mode. To my knowlage you are the only one witch have implemented this so I decided to try to ask you.

Thanks.

**Comment by duckbill007** [comment]
Отвечу, как ответил SciresM мне на тот же самый вопрос: "You should RE it yourself"

**Comment by shadow2560** [comment]
OK so you do the same thing that you probably haven't apreciated, a realy strange attitude that I will never understand. Thanks anyway for your work.
