### ISSUE TITLE
external usb drive detection

### ISSUE THREAD

**Issue by Mintume** [rashevskyv/dbi#128]
Hi,
It's wonderful program. As we store our downloaded games on external drives which are NTFS formatted and are 1TB, 2TB and more. Currently, this program doesn't support NTFS drives. It would be great to have this feature. I currently use Tinwoo which works with 2TB NTFS drives.

Hope you can make backend for MacOS just like windows system.

**Comment by duckbill007** [comment]
Нет. Этого не будет из-за ограничений лицензии.

**Comment by rashevskyv** [comment]
Backend works fine on macos. You should use 'dbibackend' and launch it eith
python3

нд, 11 вер. 2022, 16:09 користувач Duckbill ***@***.***> пише:
