### ISSUE TITLE
cant read hdd/flashdrive

### ISSUE THREAD

**Issue by ctrlpaste** [rashevskyv/dbi#13]
is can read over my mobilephone with mtp responder, but feature before with ams-kips is cant read hdd/flashdrive, for sure the menu also is gone, i run dbi over applet mode also try full ram access, isnt appear. i use latest atmosphere on 10.2.0 with latest sigpatches

**Comment by duckbill007** [comment]
Did you create flag file sdmc:/switch/dbi.libusbhsfs ?
