### ISSUE TITLE
ubuntu 20.04 shows multiple cameras when opening mtp connection none can be opened

### ISSUE THREAD

**Issue by crlink271986** [rashevskyv/dbi#130]
so I'm on the latest Ferran OS (Based on Ubuntu 20.04 focal fossa) when i tell dbi to connect via mtp the file explorer or whatever kde calls it shows 10 "cameras" callled DBI trying to mount one yeilds a timeout error after a few seconds i really rather not use ftp or god forbid back to windows just to install nsps

**Comment by duckbill007** [comment]
Проверил на чистой Ubuntu 20.04. Работает как должно.
