### ISSUE TITLE
SMB share for DBi?

### ISSUE THREAD

**Issue by Jonny0r** [rashevskyv/dbi#131]
Dear Sir,

First thank you for your awesome tool, i really appriciate that much work and that much love that you spend on your software.

Im looking already for this since quiet a long time and i really wondering if i am the only one that wants to use it :D 
Is it not possible to add in any future versions of DBI also an SMB share option? As i guess this would be an pretty cool thing if 
you could install games from your own home server / nas storage.

Thanks in advance and keep on :)

**Comment by duckbill007** [comment]
SMB в планах нет и не будет. HTTP и FTP вполне достаточно.
