### ISSUE TITLE
title from USB

### ISSUE THREAD

**Issue by Hafidzgtg** [rashevskyv/dbi#134]
DBI 432 the trend is the same =
The install speed is slower than v358 as a whole.

DBI 432 tested for fast MTP responder speed, but not title from USB.
But the v358 speed is +/- average in all lines (title from USB, Flashdisk & MTP responder).

V432 install title from USB Slow
V358 install title from USB fast👍🏻

Thanks 🙏🏻

**Comment by duckbill007** [comment]
Работает как задумано.
