### ISSUE TITLE
DBI 435 - crash system in exit from dock mode

### ISSUE THREAD

**Issue by lowburger** [rashevskyv/dbi#135]
Hi,

I find problem with DBI 432 existing only on dock mode. When exit DBI will cause crash atmosphere in album, or error on full RAM mode. On handheld: no problem.

This problem only with DBI setting: direct exit to homescreen NO

I check with DBI 415 and DBI 389, here no problems on dock mode.

Thx

**Comment by lowburger** [comment]
DBI 435 - now setting direct exit to homescreen doesn't matter YES or NO. DBI always crash in exit in dock mode.

**Comment by pixeltester** [comment]
Same issue here with DBI 436, only when the Switch is docked. Exiting from applet mode (blue screen in DBI) causes atmosphere to fatal with 2168-0002 error. Exiting from override mode (black screen in DBI) causes "The software has closed because an error occured".

**Comment by duckbill007** [comment]
На кефире не повторяется.

**Comment by neomhor** [comment]
dbi 439 still crashs on exit while in dock mode
