### ISSUE TITLE
FTP install from Smartphone (android)

### ISSUE THREAD

**Issue by Ludo-draw** [rashevskyv/dbi#137]
Im trying to install a NSP from my smartphone using a ftp client. Everytime i try to install (microsd install) it shows the tranfer percent in the client, but as soon as the percent bar starts to load in DBI, it just stops in about 80%.
Ive tried other NSPs, other ftp clients and got the same result (Sorry my bad english, not my country language)

**Comment by duckbill007** [comment]
Повторить не удаётся. Проверь уровень сигнала, отсутствие помех. Если не получается стазу ставить, сначала перкинь на карту и ставь с карты.

**Comment by Ludo-draw** [comment]
Its not an network issue, i can normally install from FTP using the same network with my pc,  and i can conecto normally the smartphone to the console, only when dbi installs i get this problem, it just stops.
