### ISSUE TITLE
dbibackend has wrong line endiing

### ISSUE THREAD

**Issue by nrlquaker** [rashevskyv/dbi#138]
Its not possible to launch it on macOS:
`/usr/bin/python3^M: bad interpreter: No such file or directory`

Can be easily fix changing line ending to Unix. Fox example in vim: `:set fileformat=unix`

The file in the repo is ok, I'm talking about the one in releases inside the `dbibackend.tar.xz`

**Comment by duckbill007** [comment]
Маки не подерживаются.

**Comment by rashevskyv** [comment]
Can you pack it in tar.gz in correct format please? Theoretically it would
be enough for using this archive for all users

пн, 24 жовт. 2022, 17:55 користувач nrlquaker ***@***.***>
пише:

**Comment by rashevskyv** [comment]
@nrlquaker please try from this release https://github.com/rashevskyv/dbi/releases/tag/438

**Comment by nrlquaker** [comment]
@rashevskyv working as expected. Thanks.
