### ISSUE TITLE
[REQUEST] Access to the folder Firmware 

### ISSUE THREAD

**Issue by deejay87** [rashevskyv/dbi#14]
Hi
If you can add the Access to the folder Firmware to remove the update systeme message (usefull on emunand)
Thanks

**Comment by rashevskyv** [comment]
You can remove nag with clean orphaned files

пн, 28 дек. 2020 г., 23:12 deejay87 <notifications@github.com>:

**Comment by deejay87** [comment]
Perfect thanks
