### ISSUE TITLE
DBI crashing on exit in docked mode only

### ISSUE THREAD

**Issue by pixeltester** [rashevskyv/dbi#142]
Hello,

I have been testing and I have some additional information about https://github.com/rashevskyv/dbi/issues/135 where dbi crashes when exiting in docked mode.

I tested it with KEFIR 656 and DBI 438, a completely clean installation with nothing else on the microSD card.

The issue is still there: exiting from applet mode (blue screen in DBI) causes atmosphere to fatal with 2168-0002 error. Exiting from override mode (black screen in DBI) causes "The software has closed because an error occured".

Here is the crash report from KEFIR:

https://gist.github.com/pixeltester/a311a1df666361627755da1fca950006

This crash will only occur after ShowCacheWarmingIndicator has finished spinning. If you exit in the first few seconds before the indicator finishes spinning then the crash will not occur, so it seems this crash is related to the caching operations introduced in version 432 of DBI. The indictor itself is not the cause of the problem, you can turn it off and the same issue will occur.

**Comment by rashevskyv** [comment]
Fixed in [455](https://github.com/rashevskyv/dbi/releases/tag/460)

**Comment by rashevskyv** [comment]
Tested it with completely clean installation with nothing else on the microSD card.

**Comment by pixeltester** [comment]
@rashevskyv  just tested it and it's not fixed in 460 sadly.

**Comment by rashevskyv** [comment]
> 2022-12-14.17-11-36.mp4

Y version on screencast is 455?

**Comment by rashevskyv** [comment]
Try 650

чт, 15 груд. 2022 р., 00:16 користувач Ammako ***@***.***>
пише:

**Comment by pixeltester** [comment]
Looks like the issue is completely fixed in 462, thanks!
