### ISSUE TITLE
"TitleID Not Found" when working in fresh emuNAND

### ISSUE THREAD

**Issue by ToxiClay** [rashevskyv/dbi#144]
HOS version: 15.0.0
AMS version: 1.4.0
DBI version: 438

When working with a freshly-created emuNAND, DBI consistently crashes in a way I can't explain. Working in my sysNAND is OK.

Steps to reproduce:

1. Create fresh partition-based emuNAND via Hekate.
2. Boot into emuNAND, then launch DBI.
3. Access "Browse installed applications."
4. Attempt to access an application leading off with `M` or `S`. The few applications I have that start with `G` (art books included in the Atelier Mysterious Trilogy Deluxe Pack) are fine.
5. Observe a crash.

The crash message is:

```
An error occurred.
[0x00000E05] TItleID not found

Press any button to exit.
```

Note: DBI apparently stores error reports, but I can't find where they get stashed. I'd love to attach one, if you can help me figure out where they go; they're certainly not showing up in the DBI logs directory as configured in `dbi.config`.

# Screenshot
![2022110222355300-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/13796683/199637915-c130d13f-ea81-41a6-94d1-5e2a1e5f8296.jpg)

**Comment by duckbill007** [comment]
Должно быть исправлено в 490
