### ISSUE TITLE
XCZ cannot be installed from USB HDD

### ISSUE THREAD

**Issue by jacoghi** [rashevskyv/dbi#145]
Hello, first of all, thanks for this piece of software, it's awesome. I noticed it does not currently support xcz using block compression, is it possible to add support for that? Using latest 439. Thanks

EDIT: I just tried with solid compression and it's not working either. Installing from a USD HDD. Everything else seems to work, nsp and nsz, however xcz is a no-go with 439. Tried rolling back and no version between 439 and 415 works. Didn't go any older than that. When selecting XCZs, is shows "Nothing to install".
Atmosphere 1.4.0, EmuMMC, HOS 15.0.0

**Comment by duckbill007** [comment]
Не работает только с USD HDD? С карты памяти или MTP работает?

**Comment by duckbill007** [comment]
Если используется nsz от nicoboss, то он создаёт невалидные XCZ. Как минимум - неправильный hash table в заголовке.

**Comment by duckbill007** [comment]
Кроме того - в заголовке XCZ после ncz.py в поле hfs0_header_size указано абсурдное значение.

**Comment by jacoghi** [comment]
I just tried with the MTP Responder method. Results:
- The solid compression XCZ DID NOT work;
- That file (which did not work through DBI MTP Responder) was used to decompress back a XCI, which was installed via MTP Responder successfully;
- The same XCI was then compressed using block compression XCZ, which was installed via MTP Responder successfully;
- The XCZ block compression was then copied to a USB HDD, and COULDN'T be installed
Results are here:
[https://imgur.com/a/Xcd9pOy](https://imgur.com/a/Xcd9pOy
)

(Atmosphere 1.4.0, tested with both 14.1.2 and 15.0.0, Firmware and CFW don't seem to have any effect on this. DBI 439, xcz made with nsz 4.1.0, solid / block compression, level 22 - id 0100317013770000)

**Comment by duckbill007** [comment]
Исправлено в 440.
