### ISSUE TITLE
DBI crashes when exiting on HOS 15.0.0

### ISSUE THREAD

**Issue by jacoghi** [rashevskyv/dbi#146]
Doesn't matter if choosing exiting straight to main menu or to hb menu, it crashes producing an error

**Comment by duckbill007** [comment]
У меня никак не получается повторить падение на выходе. Какие точно версии всего используются? Включая hbloader. И как запускается DBI? Title mode or applet mode?

**Comment by jacoghi** [comment]
I just tried this out. DBI 439 DOES NOT crash when undocked, and always (10/10) closes correctly.
However, when in docked mode, with a USB HDD connected, it does crash 90% of the time (9/10) if a USB HDD operation is performed. Trying to install, successfully installing files, anything will cause the crash "The software was closed because an error occurred".
If the USB HDD is just accessed (meaning no attempt to install), it crashes roughly 50% (5/10) of the time, so I guess it's directly related to the USB HDD operations.
These are all in title mode.

**Comment by pixeltester** [comment]
There is already an issue for this, why make a second one? https://github.com/rashevskyv/dbi/issues/142

Also the older one that was closed: https://github.com/rashevskyv/dbi/issues/135

**Comment by jacoghi** [comment]
If the developer believes this to be a duplicate, he'll mark it as such, you yourself are saying 142 is not necessarily related to USB, so... what's your point?

**Comment by pixeltester** [comment]
Containing all information in a single issue is preferable (obviously?) Your issue was made for crashing on exit; exactly the same as an existing issue. It's not that hard to look at 10 issues and not make a duplicate is it? This isn't a repo with hundreds of issues.

**Comment by jacoghi** [comment]
@pixeltester, I appreciate your input very much... Now could we please move one, stay on topic and not make out of this another completely pointless silly internet discussion?

**Comment by pixeltester** [comment]
You asked me what my point was and I answered. Nothing else to add, hopefully duckbill can find the issue.

**Comment by rashevskyv** [comment]
Fixed in [455](https://github.com/rashevskyv/dbi/releases/tag/460)
