### ISSUE TITLE
[Android] DBI cant install more than 4GB xci/nsp using MTP

### ISSUE THREAD

**Issue by yuuhack** [rashevskyv/dbi#147]
I am using samsung note 10 to install 5gb & 7gb games through mtp responder using otg. However, after copy/move the respective file to MicroSD install folder, my android said the file not copied. Then ,i tried install both games update which is 500mb & 200mb and both succesfully installed. Im using Fat32 formatted 1tB microsd. DBI 439 both applet & extra ram mode. 
This is only happened when using android. I have no problem installing any game size  through mtp responder using PC. Is this the limit for fat32 sdcard formatted?Any workaround for this problem?

**Comment by duckbill007** [comment]
Насколько я знаю, это проблема Самсунга. На pixel 5 ставится без проблем.
