### ISSUE TITLE
Cannot dump BASE files with DBI

### ISSUE THREAD

**Issue by iero19** [rashevskyv/dbi#148]
Hello! I have an Erista (Patched) Switch that I recently had a modchip installed on. I am planning on dumping my eShop games to install them to emuNAND but I am running into an issue where the BASE NSP that I'm seeing in MTP Responder mode is only 16-bytes. I am currently using DBI 439, with Atmosphere 1.4.0 and firmware 15.0.1.

**Comment by rashevskyv** [comment]
Not a DBI issue. Just made emunand and copy nintendo folder to emummc/sd00 folder
