### ISSUE TITLE
Please build with latest libusb for ntfs support

### ISSUE THREAD

**Issue by ginkuji** [rashevskyv/dbi#15]
Hi please release a new version with the latest libusb 
The new one has ntfs support
https://github.com/DarkMatterCore/libusbhsfs/releases/tag/v0.2.2

**Comment by duckbill007** [comment]
No way

**Comment by ginkuji** [comment]
Ok. Your call.

Sent from Yahoo Mail on Android 
 
  On Sun, Jan 3, 2021 at 5:42 PM, Duckbill<notifications@github.com> wrote:   


No way

**Comment by duckbill007** [comment]
It has incompatible license
