### ISSUE TITLE
Some new game like j**tdance 2023 or Taiko no Tatsujin Rhythm Festival can't dump they offline datebase.

### ISSUE THREAD

**Issue by illyasever-lol** [rashevskyv/dbi#151]
![111](https://user-images.githubusercontent.com/62844721/204143115-38bbc152-6b12-4214-984f-5e18895083d5.jpg)
This game can download they offline datebase on TF:/Nintendo/save.
![23332](https://user-images.githubusercontent.com/62844721/204143160-37b22fdd-8052-4c3f-8086-b441e53835c7.jpg)
But i can use dbi saw this save datebase.
Its any other method to dump it  or use other tools?
![20221127231704](https://user-images.githubusercontent.com/62844721/204142902-e1756e86-0f54-45a1-93a9-a43f72a06dce.jpg)
I saw this file kind is NAX0.

Thanks for your help~~

**Comment by duckbill007** [comment]
Вообще ничего не понял. В чем именно проблема?

**Comment by illyasever-lol** [comment]
Thanks for reply.The question is dbi whether can dump or decrypt the files on TF:/Nintendo/save.

**Comment by duckbill007** [comment]
Откройте "Browse saves" и сделайте скриншот списка с игрой Just Dance

**Comment by duckbill007** [comment]
А также откройте карточку игры через Browse installed applications и сделайте скриншот вкладки Saves.

**Comment by illyasever-lol** [comment]
![傲游截图20221129205041](https://user-images.githubusercontent.com/62844721/204533757-6ccd27b2-ba66-471f-a16a-b0c640223b5b.jpg)
![傲游截图20221129205025](https://user-images.githubusercontent.com/62844721/204533769-9e2baa71-3668-44c2-891e-d036e4c327fe.jpg)

here is the Browse installed applications screenshot.
I find in jksv,this offline datebase is in Cache operation.I can dump it to tf card,but cant import it to other device.
