### ISSUE TITLE
Files with special characters disappearing after dump to NSP

### ISSUE THREAD

**Issue by rossbeck** [rashevskyv/dbi#153]
Some titles with special characters such as ® (found in many titles) will dump successfully but the nsp files do not become available in the dump folder. 

No errors are shown, but the file gets lost during file creation/renaming. DBI reports a successful dump but there are no resulting .nsp files in the dump folder.

IE: Tetris®Connect

**Comment by duckbill007** [comment]
Исправлено в 490
