### ISSUE TITLE
What's wrong with the latest DBI version?

### ISSUE THREAD

**Issue by Olfdev** [rashevskyv/dbi#154]
Hello,

Since the last version, a lot of things aren't working anymore:
- MTP doesn't show any folder in Windows so it cannot be used anymore.
- FTP doesn't show copy progression anymore and lack informations when FTP server is successfuly created. I only get a "Accepting conections (typo in connections word btw) on 192.0.0.0:5000" and that's all.
- In FTP mode, I need to quit FTP and go back if I want to copy a second file or I get a "broken pipe" error.

Rolled back to the previous version and everything's working fine.

Thanks!

**Comment by mspykerez** [comment]
Which version are you referring?
I'm asking because there is a newer version (455) posted on a forum that is not on github yet.

**Comment by Olfdev** [comment]
Thanks, I tried the 455 version from GBATemp, MTP server is back in business!

**Comment by Olfdev** [comment]
v455 is working just fine.
