### ISSUE TITLE
Game size not showing correctly 

### ISSUE THREAD

**Issue by DefinetlyNotPirating** [rashevskyv/dbi#158]
When i installed Cuphead over USB using DBI backend the installed applications tab in DBI on the switch showed the games size to be 432.00 TB. Game works fine but when looking at the size of the the parts individually all sizes were right. Also could not move the game to SD card from emuNAND even though i had 124gb of free space. I was using DBI v462.

**Comment by duckbill007** [comment]
На 490 не повторяется
