### ISSUE TITLE
XCOM2: Wrong Program ID for War of the Chosen

### ISSUE THREAD

**Issue by masagrator** [rashevskyv/dbi#159]
This happens in both game file browser and MTP mounting.

When mounting base, it shows launcher with `Program 0` and main game with `Program 1`.
Update is showing launcher with `Program 0` and War of the Chosen as `Program 1` <- and this is wrong, since WotC has Program ID 2. Main game was not updated through this patch, that's why it's not showing when mounting update.

**Comment by duckbill007** [comment]
Fixed in 464
