### ISSUE TITLE
Virus Detected on dbi backend

### ISSUE THREAD

**Issue by jwillis7** [rashevskyv/dbi#16]
Hi all, i can't download the backend program, it says Failed - Virus detected. I can't work around this to allow me to keep the file anyway as even when i click that, the file still doesn't download

**Comment by rashevskyv** [comment]
So turn off your antivirus or use dbibackend from tx archive and comand
promt or do not use backend

пт, 1 янв. 2021 г., 15:36 jwillis7 <notifications@github.com>:

**Comment by melterx12** [comment]
so any reason as to why your exe is reported to include a virus?

**Comment by Masamune3210** [comment]
False Positives are unfortunately a rampant thing in open source projects, and unfortunately, there isn't a way to keep anti-viruses from thinking that they are malicious when they really aren't
