### ISSUE TITLE
Objetc deleted

### ISSUE THREAD

**Issue by Ludo-draw** [rashevskyv/dbi#161]
When i try to install a nsp that is more than 3Gb DBI Just show this:

Session opened
Start installing to sdcard
Received 0b <0.00 MB/sec>

Deleting "nspname".nsp
Object deleted

aditional information: Im trying to install from smartphone android via usb-c cable, every game that is less than 3G works normally

**Comment by duckbill007** [comment]
Ищи проблему в своем смартфоне. У меня работает нормально

**Comment by rogerwilco84** [comment]
What phone do you use?
