### ISSUE TITLE
xcz and nsx not installing from USB HDD

### ISSUE THREAD

**Issue by jacoghi** [rashevskyv/dbi#164]
DBI 467. xcz and nsz files keep showing "File is corrupt" when trying to install via USB HDD. Same files install perfectly via MTP responder. When more than a file is selected, there's no feedback from the software at all, the user doesn't know what's going on / dbi becomes unresponsive.

**Comment by duckbill007** [comment]
У меня нет USB HDD, но на USB Flash не повторяется.

**Comment by jacoghi** [comment]
Anything I can help you debugging?
