### ISSUE TITLE
Allow CLI, deamon (no tkinter) option

### ISSUE THREAD

**Issue by niyazaki** [rashevskyv/dbi#165]
As much as I love DBI. I plan on automatically install games when plugging my switch to my server where all my legal games are. The idea is that I cannot use the new version of this script as tkinter cannot be used headlessly on my server (linux based).

My actual workaround is [this script](https://github.com/cyb3rwarden/dbibackend/blob/0885ef67edf28cbca30fb2c193ad7ab9a62786f7/dbibackend/dbibackend.py) that I updated a bit. I would love to help you implement this CLI option or testing it if needed.

**Comment by rashevskyv** [comment]
You can pull request changes if you want to. Will be appreciated
