### ISSUE TITLE
Can't save the FTP home server address

### ISSUE THREAD

**Issue by JohnDoeCN** [rashevskyv/dbi#166]
DBI v462 & v467. When I Connent to my FTP home server , I have to input the address such as `ftp://username:password@192.168.1.111:2121/` , and DBI works just fine, but next time when I quit and run DBI again I hit the "Connect to server" button and I have to type the FTP server address again. DBI seems can't save the address for me. I Couldn't find any help in the [ENGLISH GUIDE](https://github.com/rashevskyv/dbi/blob/main/README_ENG.md).

**Comment by duckbill007** [comment]
Connect to server используется для разового быстрого подключения. Если Нужно постоянный коннект к одному и тому же серверу, занеси его в конфиг.

**Comment by JohnDoeCN** [comment]
Problem solved. Turns out that I hadn't delete the ";" in dbi.config. Haha. Thanks a lot.
