### ISSUE TITLE
Colors not described in readme

### ISSUE THREAD

**Issue by hawkeye73** [rashevskyv/dbi#168]
Can someone help to describe the different color meanings?

GREEN - Not installed
LIGHT GREY - ?
DARK GREY - ?
WHITE - Focus
LIGHT BLUE - Selected

Because I see installed and non-installed with light and grey dark.

**Comment by rashevskyv** [comment]
Added to readme. See on next update

**Comment by hawkeye73** [comment]
Thanks for completing this info! Appreciated.
