### ISSUE TITLE
Updating cheats

### ISSUE THREAD

**Issue by mspykerez** [rashevskyv/dbi#169]
Many people get their cheats from this [RAR/ZIP](https://gbatemp.net/download/cheat-codes-sxos-and-ams-main-cheat-file-updated.36311/) file that with every update becomes bigger and bigger which makes the job of dragging all the cheats to the SDCard a slow painfully experience.

We could just drag the cheats only for the games we have installed and eliminate lots of bloat that way but it's an inconvenience to pick every game we want manually when there's lots of them!

Is there any way to make DBI automatically filter the compressed cheat file in order to only accept the cheats for the games we have installed (overwriting existing ones if an update is detected) when we feed the compressed cheat file via MTP or something ?

**Comment by duckbill007** [comment]
Нет, такой возможности нет. Для обновления читов можно использовать AIO updater

**Comment by mspykerez** [comment]
@duckbill007  AIO looks to do exactly what I want but it does not work offline, you have to connect the Switch to the internet and I don't like to have my modded Switch connected to the internet.

Perhaps it would be easier for you to point DBI to this cheat database https://github.com/HamletDuFromage/switch-cheats-db or this one https://github.com/blawar/titledb both of which seem to get its cheats from https://gbatemp.net/download/cheat-codes-sxos-and-ams-main-cheat-file-updated.36311 converted to .json file format.

So it would be something like how DBI currently checks for missing updates & DLC ?
