### ISSUE TITLE
Backend crashes on macos Big Sur

### ISSUE THREAD

**Issue by URBANsUNITED** [rashevskyv/dbi#17]
Hi!
Can't get the backend working.
It crashes with this result

andi@iPro-von-Andi ~ % python3 /Volumes/osX_DaTa/-\=Benutzer\=-/andi/Downloads/dbibackend\ \(1\)               
macOS 11 or later required !
zsh: abort      python3 /Volumes/osX_DaTa/-\=Benutzer\=-/andi/Downloads/dbibackend\ \(1\)

The plugin for the crash is
_tkinter.cpython-38-darwin.so
as it looks like

Crash report:
[https://pastebin.com/YvGKP3V1](https://pastebin.com/YvGKP3V1)

Thanks

URBANsUNITED

**Comment by rashevskyv** [comment]
You cam try https://github.com/lunixoid/dbibackend.

**Comment by URBANsUNITED** [comment]
Hi!
Even the new version of backend doesn't work:
![Bildschirmfoto 2021-01-20 um 18 29 51](https://user-images.githubusercontent.com/6212300/105212483-d0493480-5b4d-11eb-8e52-bc8914a936da.png)
The backend https://github.com/lunixoid/dbibackend. doesn't work either.

Other python3 app etc. work flawless.
I am on macOS 11.1

**Comment by rashevskyv** [comment]
There is no new version of backend. It is always the same. 
Author of the app have not have macos so he cannot test backend and help you with this issue.

**Comment by URBANsUNITED** [comment]
Tja... Then we simply forget it... Thanks
