### ISSUE TITLE
versions.txt format

### ISSUE THREAD

**Issue by mspykerez** [rashevskyv/dbi#171]
DBI says that versions.txt should be in format id|rightsId|version

Latest dbi.config has this VersionsURL=https://raw.githubusercontent.com/16BitWonder/nx-versions/master/versions.txt as the default source to get versions.txt but unlike the one from here VersionsURL=https://raw.githubusercontent.com/blawar/titledb/master/versions.txt the versions.txt file from the default source does not list the rightsId and I wonder if DBI will still work flawlessly without the versions.txt file containing the rightsId in it?
Furthermore can I have both sources's versions.txt files enable at the same time?

ps. also not sure if you saw my reply after closing the issue here https://github.com/rashevskyv/dbi/issues/169#issuecomment-1418258940 hence asking if it still not possible to do ? Anyway I think https://github.com/tomvita/Breeze-Beta can do what I'm looking for albeit it doesn't support MTP.

**Comment by duckbill007** [comment]
Это не форум подержки
