### ISSUE TITLE
dbi 486 drop input bug

### ISSUE THREAD

**Issue by lowburger** [rashevskyv/dbi#172]
Hi,

I report on dbi 486 there is new bug where controller will not work properly when first open app, many drop inputs when try to move in menu. After load spin finish all work normal. dbi 482 no problem.

Thx

**Comment by pixeltester** [comment]
That's not something new in 486. It happened even on older versions when the ShowCacheWarmingIndicator stuttered, most likely when a a lot of games are installed because of "caching information about installed programs".

**Comment by lowburger** [comment]
OK but I only notice on recent version, 50 application and really stutter a lot when open dbi.

**Comment by lowburger** [comment]
I don't know there is fix to this but I find in new versions of DBI work very fast again... thx.
