### ISSUE TITLE
Install title from USB HDD

### ISSUE THREAD

**Issue by TTghostsemir** [rashevskyv/dbi#174]
Is it possible to implement Install Title from USB HDD in DBI?

**Comment by rashevskyv** [comment]
Title? It is already implemented

пн, 13 лют. 2023 р., 20:49 користувач TT-ghost_semir <
***@***.***> пише:

**Comment by TTghostsemir** [comment]
Yes so NSP , XCI , NCZ , NCA Install from a HDD/SSD

**Comment by rashevskyv** [comment]
It was implemented long time ago

пн, 13 лют. 2023 р., 21:11 користувач TT-ghost_semir <
***@***.***> пише:

**Comment by duckbill007** [comment]
Я не понимаю, так сложно перед тем как писать тикет проверить?

**Comment by TTghostsemir** [comment]
I have no option for that I use DBI 480 (latest) I have also check the Config

**Comment by rashevskyv** [comment]
What option? Put your usb in exfat or fat32 to console and dbi should see
it. Brows to it and install from it.

вт, 14 лют. 2023 р., 12:38 користувач TT-ghost_semir <
***@***.***> пише:
