### ISSUE TITLE
Delete Title ONLY without deleting both DLC/Updates

### ISSUE THREAD

**Issue by vegedb** [rashevskyv/dbi#176]
As per title.
Hope this is a thing

More context: 
Base game: 15GB
Updates/DLC: 10GB

When "FAILED" base game happens during tinfoil install (maybe 10/15GB), it will skip it and continue downloading DLC/UPDATES.

After everything finishes, the "FAILED" base game already takes incomplete 10GB and we can't redownload it without deleting updates/dlc as well.

**Comment by rashevskyv** [comment]
Browse installed -> %game_name% -> delete what exactly you need

ср, 15 лют. 2023 р., 17:55 користувач vegedb ***@***.***>
пише:

**Comment by vegedb** [comment]
> Browse installed -> %game_name% -> delete what exactly you need

There must be a bug then:
Total size: 26GB
Total of contents (dlcu/pdates) only 10GB

In "Browse Installed", No "Application". Only DLC/UPDATES.

**Comment by duckbill007** [comment]
В чём баг-то?

**Comment by rashevskyv** [comment]
You should provide screenshots
