### ISSUE TITLE
DBI 490 Cleanup orphaned files bug

### ISSUE THREAD

**Issue by lowburger** [rashevskyv/dbi#177]
Hi,

I report on dbi 490 english version there is bug when try to use Cleanup orphaned files: 

[0x000fa402] (2002-2002) Sd Card Access Failed

Error happen on album or full RAM mode.

After four attempt works...

Thx

**Comment by lowburger** [comment]
After more test I find sometimes work normal, other times this error appear. I don't know cause.

**Comment by rashevskyv** [comment]
Check your sd for errors. And it should be formatted in fat32

**Comment by lowburger** [comment]
SD no problem no error and fat32, but in new versions of dbi the problem stop so I will close issue and keep to check it. Thx!
