### ISSUE TITLE
Underclocking and overclocking question

### ISSUE THREAD

**Issue by pixeltester** [rashevskyv/dbi#179]
I noticed if we have the version of sys-clk from https://github.com/KazushiMe/Switch-OC-Suite running then DBI can't set the CPU underclock or CPU overclock boost mode during installation properly with the `OptimizeClockSpeed=true` setting. The GPU looks like it works normally.

For example: 

- open DBI, clock is set to 612 / 76.8 but immediately CPU increase back to 1020, GPU remains at 76.8. 

- After this begin installing file with MTP, CPU clock increases to 1785 but again immediately decreases 1020, GPU remains at 76.8.

Since Switch-OC-Suite is quite popular, is there any way to fix this on DBI's side so that the CPU setting for overclock or underclock works properly? In games CPU boost works normally so maybe there is another way to set this? Thanks

**Comment by Masamune3210** [comment]
By setting optimizeclockspeed=true, you are telling DBI to handle raising and lowering the clocks itself to accelerate some actions and save battery power/temp elsewhere, having another tool interact with the clocks at the same time is a recipe for disaster. Would't it make more sense to disable the OC-Suite's clock manipulation temporarily while using DBI?

**Comment by duckbill007** [comment]
Совершенно верно. Данная функция в DBI не совместима с различными автоматическими решениями. Используйте что-то одно.
