### ISSUE TITLE
[REQUEST] Background

### ISSUE THREAD

**Issue by deejay87** [rashevskyv/dbi#18]
Hi, 
is it possible to add the possibility of placing a wallpaper or a choice of color
Thanks :)

**Comment by rashevskyv** [comment]
Possible, but not necessary.

сб, 23 янв. 2021 г., 14:49 deejay87 <notifications@github.com>:

**Comment by deejay87** [comment]
Yes, i understand that :)
It's just a "request" from lot of people i help on my Discord/Youtube who love custom themes etc
