### ISSUE TITLE
Check for title updates not working

### ISSUE THREAD

**Issue by w1lk1ns** [rashevskyv/dbi#180]
Downloading update list ... [FAILED]

I believe the issue is the URL to 16BitWonder has changed. DBI shows it as "https://github.com/16BitWonder/nx-versions/master/versions.txt" where if you go to 16BitWonders Github the URL to the file is "https://github.com/16BitWonder/nx-versions/blob/master/versions.txt"

**Comment by duckbill007** [comment]
Текст в конфиге DBI это просто пример. Вы должны сами найти и указать правильный url.

**Comment by w1lk1ns** [comment]
Weird, it used to work fine. How do i configure it? i don't see it in the dbi.config file

**Comment by w1lk1ns** [comment]
Strange, it used to work before. I've double-checked the dbi.config file and don't see any issues. Not sure whats going on as it loads fine on my desktop
