### ISSUE TITLE
Fw16.0.0  AMS 1.5.0 Dbi can't install nsp/xci.

### ISSUE THREAD

**Issue by illyasever-lol** [rashevskyv/dbi#182]
Fw:16.0.0 Ams 1.5.0
bootload:hekate fss0 or ams fusse
Install mode:applet model mtp/app mode mtp
error code: 2168-0002（0x4a8）

error img:
![504002677](https://user-images.githubusercontent.com/62844721/220948333-481a9929-6306-422a-9d32-c1c23ae59458.jpg)

**Comment by rashevskyv** [comment]
Use 15.0.1 fw. Never tested on 16.0.0 and officially not supported

**Comment by illyasever-lol** [comment]
OK，thanks a lot.
