### ISSUE TITLE
Support for OFW 16.0.0 AMS 1.5.0

### ISSUE THREAD

**Issue by djskual** [rashevskyv/dbi#183]
Unable to install nsp with mtp responder FW16.0.0 AMS 1.5.0 last Sigpatches
all is updated, but cant install nsp, DBI 490 can't write to PLACEHOLDER.

**Comment by rashevskyv** [comment]
16.0.0 is not supported.

чт, 23 лют. 2023 р., 19:40 користувач djskual ***@***.***>
пише:

**Comment by xlaw888** [comment]
> 

I hope you can fix it.. Thanks man!

**Comment by duckbill007** [comment]
Исправлено в 499+

**Comment by Blackr41n** [comment]
Where i cam download 499+?

**Comment by rashevskyv** [comment]
Whait for it be released

**Comment by Blackr41n** [comment]
Ok, thank you.

**Comment by blawar** [comment]
> Исправлено в 499+

What was the issue?

**Comment by Masamune3210** [comment]
my guess is its this 
![image](https://user-images.githubusercontent.com/1053504/221367044-304a2607-0e5c-4ecd-9147-db2bc33f1f0d.png)

**Comment by duckbill007** [comment]
> What was the issue?

Changed IPC for some ncm calls

**Comment by blawar** [comment]
> Changed IPC for some ncm calls

Which call(s) if you don't mind me asking? I suspect something related to cleaning orphaned files and reading installed NCA's? I believe we take different approaches to these tasks.

**Comment by duckbill007** [comment]
Actually all that takes contentid or placeholderid. In 16.0.0 they changed alignment of these arguments.
