### ISSUE TITLE
Error cleaning placeholders

### ISSUE THREAD

**Issue by josete2k** [rashevskyv/dbi#184]
DBI 490/493

Looking for obsolete titles
Looking for orphaned files on SD
Cleaning placeholders... [FAILED]
[0x0000f601] (2001-0123) Unknown error

Emummc in hidden partiton

Same with nsp install... 

AMS 15.0.0 FW 16.0.0

Nedded recompiling for fw 16 maybe?

Thanks in advance

**Comment by Masamune3210** [comment]
Wait for update for support for 16.0.0

**Comment by josete2k** [comment]
Ok, thanks

**Comment by duckbill007** [comment]
This error not related to 16 directly. Try to turn off all sysmodules and try again on clean atmo.

**Comment by Masamune3210** [comment]
Latest Atmos release talks about having to have adjusted placeholders so I just assumed it would need a update, mb

**Comment by josete2k** [comment]
> This error not related to 16 directly. Try to turn off all sysmodules and try again on clean atmo.

Downgrading to 15.0.1 solves this issue...

So I assumed that is a 16.0.0 related issue.

**Comment by smiglo5** [comment]
> > This error not related to 16 directly. Try to turn off all sysmodules and try again on clean atmo.
> 
> Downgrading to 15.0.1 solves this issue...
> 
> So I assumed that is a 16.0.0 related issue.

https://github.com/rashevskyv/dbi/issues/183
Already confirmed it will work with next release of DBI.
