### ISSUE TITLE
DBI 502 English

### ISSUE THREAD

**Issue by pixeltester** [rashevskyv/dbi#185]
Sorry I know usually issues are not for this but I'm not sure where else to write it. This message is to let duckbill know that everyone, non-Russians included, thinks DBI is amazing software. I don't read or care about gbatemp and looking at the download stats here I think many thousands agree with me. Sorry to hear that they insulted you. Thanks duckbill!

**Comment by SiTWulf** [comment]
One of the best solution is posting the App in the [HomebrewAppStore](https://apps.fortheusers.org/switch)

**Comment by MultiKoopa** [comment]
I 100% agree

**Comment by MultiKoopa** [comment]
I 100% agree with pixel tester

**Comment by gelson-zord** [comment]
Yeah, after some Tinfoil shops closed, DBI is my favorite homebrew app! 

Maybe some offenses come to russian apps/products/people due to the recent geopolitical occurencies. 

Cheers from Brazil!

**Comment by dotmehdi** [comment]
I totally agree, and I wanted to thank you for this amazing software that is waaaay more than just a dummy title installer. I always have it installed on the consoles I hack and it makes me win a lot of time. So thank you very much from the french Switch community !!

**Comment by WanderMax** [comment]
how about extract language fils to external .ini fie?

**Comment by jagurxe** [comment]
men i am mexican, need a version of spanish, english no matter for me, fuck that gbatemp guys, DBI its the great app for switch, for much, can do everything in administration and installation

**Comment by lowburger** [comment]
dbi amazing program and Gbatemp it's one of worst place in Switch scene, forget it!!!

**Comment by Medel87** [comment]
In my opinion no one insult DBI developer, and with this war the people that is affected don't have nothing to do with it, stop this please

**Comment by gelson-zord** [comment]
@jagurxe I don't know any rus lang too, but the options in the app are on the same position, like the one I use most is "Run MTP server", so I just got to that option and used the newer version without problems. I had problem with 490 that crashed the homebrew, and this version fixed it!

**Comment by orangecleric** [comment]
Great work on DBI @duckbill007 ! Thank you

**Comment by sthetix** [comment]
We need to separate political views from community homebrew apps. DBI is an excellent app.

**Comment by djskual** [comment]
Hello, sorry to heard some people are bastards. Hope you will don't care about us.
DBI is THE application i use on switch!!!
Keep the good work.

**Comment by Deathreed** [comment]
Yeah f gbatemp and they never represent most of us. Dbi is an amazing app and what I always use on my switch. So I'm always thankful to all the devs who made this app possible.

**Comment by deejay87** [comment]
Many people do not watch what is happening on gbatemp but use this powerful homebrew which remains the most practical, quick and easy to use and all in one anyway, congratulations again for the work done, hoping for a quick return for the people who are more than fans

**Comment by nerirififi** [comment]
I am French, and I know gba temps, but majority of my country using switch and dbi doesnt know GBATEMP. So sorry for the problems you got with stupid persons, and thanks for your contribution.

**Comment by josete2k** [comment]
Well, here in Spain a fucking piece of anything can be translated to a marvelous piece of anything.

Not sure if it is the problem with gbatemp (I need context for that) but hope it helps.


Thanks.

**Comment by rashevskyv** [comment]
Thanks everyone for supporting developer of this great up!
