### ISSUE TITLE
DBI CAN'T WRITE TO PLACEHOLDER FW 16.0.0 INCOMPATIBLE

### ISSUE THREAD

**Issue by alexochoa20** [rashevskyv/dbi#186]
![Screenshot_20230225_154901_Video Player](https://user-images.githubusercontent.com/124236392/221384812-433f2f16-d6b7-4f35-a8b5-c9d87c61af81.jpg)
Any of the DBI is uncompatible with 16.0.0 firmware, it says it can't write to placeholder... I updated back to 15.0.1 to still using the app... and it worked, but the problem seems to persist in the 16.0.0 even changing to an older version. I downloaded the 490 version and proved on 16.0.0 didn't work.....

**Comment by lowburger** [comment]
Pls check to other issues before writing, you needing dbi 502...

**Comment by alexochoa20** [comment]
Excuse me, I was blind by my desperation, so sorry friend! thank you so much

**Comment by orangecleric** [comment]
@alexochoa20 Please close this issue.
