### ISSUE TITLE
English Release NRO Order

### ISSUE THREAD

**Issue by blawar** [rashevskyv/dbi#188]
Tinfoil links and installs DBI in it's homebrew section. It works by calling the github api for the latest release and either grabbing the first NRO in the release or grabbing the zip and unzipping it (and comparing file size of the NRO to see if its different than what is currently installed)

Could  you please always make the first NRO in a release the English version, that would avoid Tinfoil installing the Russian version.

As a show of solidarity, I updated DBI's description to be "Brilliant Russian Software". Some of the best programmers I have ever worked with have been Russian. Let me know if you would prefer I remove this description.

![image](https://user-images.githubusercontent.com/10227949/221423927-55830ffb-cd69-400d-b214-e8df5750109d.png)

**Comment by rashevskyv** [comment]
Sure, I will provide both NROs in release and will put to the description each versions. I think it would be fine

**Comment by rashevskyv** [comment]
Please check is it fine now?

**Comment by blawar** [comment]
> Please check is it fine now?

works great, thank you.
