### ISSUE TITLE
Feature Request: 2 config file (Sysnand and Emunand)

### ISSUE THREAD

**Issue by Asia81** [rashevskyv/dbi#192]
Hello, on my Emunand, I often use the "Cleanup orphaned files" feature, but on my sysnand I only use the "Run MTP responder" and I'm scared to misslick Cleanup Orphaned Files (because it delete tickets, and tickets deletion is was got my first switch to be banned, so I don't want this one to be).

So I would request a way to hide an option in sysnand but not emunand (maybe 2 config files, Emu.config and Sys.config) ?

Thanks for reading, whatever if it's possible or you don't want.

**Comment by rashevskyv** [comment]
If you missclick nothing bad will not happened

ср, 1 бер. 2023 р., 18:15 користувач Asia81 ***@***.***> пише:
