### ISSUE TITLE
Unable to install more than 8 files at once.

### ISSUE THREAD

**Issue by vegedb** [rashevskyv/dbi#193]
9 files or more
![image](https://user-images.githubusercontent.com/72070424/223076252-4bc06945-a040-418d-9655-559e56f162b4.png)

8 files
![image](https://user-images.githubusercontent.com/72070424/223076539-36f7666c-78e0-4085-8cb5-a5c04ac952b6.png)

7 files 
![image](https://user-images.githubusercontent.com/72070424/223076607-d65da978-a818-422e-b5ba-650600024d87.png)

Tested with a mixture of games/dlc/updates. The content is irrelevant. Its the number. Unable to install more than 8 at once.

**Comment by duckbill007** [comment]
Проверил. В описанном сценарии всё работает.

**Comment by duckbill007** [comment]
Исправлено в 510+
