### ISSUE TITLE
Fix Batch Integrity Checking

### ISSUE THREAD

**Issue by seanjsauve** [rashevskyv/dbi#199]
Batch Integrity checking is not functionally useful due to the final list often spanning pages (with no breaks). So if you don't catch them as they whip past the screen it's of no use when titles with errors list dumps the title strings one after another for pages. Neither the first time or second is easily seen without attending the entire process and luckily catching it. This would be countless times more useful with the names of the titles which had errors listed with / without the titles string. What would seriously knock the whole thing out of the park would be the ability to delete damaged titles and/or mark them and (!) marked or incomplete titles. 

This would be the ONLY software I know of which can audit the integrity of all titles and offer a solution to manage them all in one go. 

Sincerely thank you rashevskyv : THIS IS AN AWESOME TOOL IN EVERYWAY otherwise.. This is such a simple fix im sure for you. thanks

**Comment by seanjsauve** [comment]
My bad thanks to yourself as well. But @duckbill007 (or J.D.) the original comment applied.

**Comment by duckbill007** [comment]
Все подобные операции логируются (возможно, в настройках выключено по умолчанию). Поэтому, по завершению всегда можно просмотреть лог в папке логов.
