### ISSUE TITLE
Certain homebrew titles do not install correctly with DBI

### ISSUE THREAD

**Issue by FlyingBananaTree** [rashevskyv/dbi#2]
With the F2P issue fixed this is the final problem remaining with DBI installation, some homebrew titles do not install correctly.

For example you can try: https://gbatemp.net/threads/homebrew-menu-loader-legal-nsp.518433/

There are no hash errors when installing but the installation is corrupt and a black spinning icon appears in the main menu. Other installers can handle this file (awoo, tinfoil)

**Comment by rashevskyv** [comment]
https://github.com/rashevskyv/dbi/releases/tag/187

Fixed :)

**Comment by FlyingBananaTree** [comment]
> 
> 
> https://github.com/rashevskyv/dbi/releases/tag/187
> 
> Fixed :)

Works perfectly, thanks!
