### ISSUE TITLE
DBI 229 non-standard exit behaviour

### ISSUE THREAD

**Issue by FlyingBananaTree** [rashevskyv/dbi#20]
In DBI 229 exiting the application skips hbmenu and immediately returns the user to the homescreen. Is this a bug or intentional?

If intentional would you consider making this behaviour optional?

**Comment by duckbill007** [comment]
It is intentional. No this won't be optional.

**Comment by FlyingBananaTree** [comment]
> 
> 
> It is intentional. No this won't be optional.

Why not add a simple settings menu for DBI for this kind of thing? Would be very appreciated. Thanks for confirming either way.
