### ISSUE TITLE
add access to archived games in "Browse installed applications" page

### ISSUE THREAD

**Issue by Xerxes1er** [rashevskyv/dbi#206]
In the "Browse installed applications", we can find the informations on Total play time, Total launches, First Run, Last Run..

But when games are archived, we can no longer access to the details of these games, as we cannot select 0B games from the list.

It would be nice to allow the access to the archived games, even if some information will be empty in content records, or tickets for example, but the statistics information will always be accessible.

Thanks !

**Comment by duckbill007** [comment]
Сделано в 546
