### ISSUE TITLE
Submit DBI on hb-appstore?

### ISSUE THREAD

**Issue by ShagoY** [rashevskyv/dbi#208]
Hello,

First of all, I wanted to say that DBI is one of my favorite homebrew since I heard about it! It is one of my must-haves, really a good job! Thanks for your work :)

Is it possible for you to submit DBI to the Homebrew App Store?

It's a store I've been using for years and it's great to know that a package has been updated and it can also do some advertising ;-)
This project is also regularly updated and very active.
I tried to submit DBI but I lack information...

Submission : https://submit.fortheusers.org/
App : https://github.com/fortheusers/hb-appstore
Store : https://apps.fortheusers.org/switch

Regards.

**Comment by rashevskyv** [comment]
What information are you missing?

**Comment by ShagoY** [comment]
Hi,

**Author** (If you've previously submitted an app, enter the same author name.)
**Contact info** (E-mail address or Discord handle preferred.)
**Licence** (eg. GPL)
**Short description**
**Detailed description** (Longer description text, visible from the app details page)
**Banner image**  (Any image larger than 848x208 will be cropped.)
**Icon** (Avoid small text. Any image larger than 256x150 will be cropped.)

Here is an example of what will be displayed.
![image](https://user-images.githubusercontent.com/25367500/233840738-51f8aa33-75f1-46b6-8bbe-6d2dc4fc25a0.png)

**Comment by duckbill007** [comment]
Лично я против.
