### ISSUE TITLE
Not able to see "Gamecard" as an option when using MTP Responder

### ISSUE THREAD

**Issue by RagingBuracku** [rashevskyv/dbi#212]
![Screenshot 2023-04-24 173143](https://user-images.githubusercontent.com/59775668/234121440-bec52e78-2258-4dba-958a-073f4ae04d22.png)

This is all I see when I run MTP responder and I want to know how I can gain access to the game card so I can dump games

**Comment by duckbill007** [comment]
Это не форум поддержки. Ищите ответы в телеграм каналах
