### ISSUE TITLE
551 cannot connect to MTP on my OLED

### ISSUE THREAD

**Issue by ffhome** [rashevskyv/dbi#214]
The 551 version cannot connect to MTP on my OLED machine, but it can be used normally on my other non OLED machine. However, on my OLED machine, versions 542 and below can use MTP functionality normally. It is certain that the issue is not caused by the Tesla plugin.

Computer: Windows 11 x64

OLED Switch: System version 16.0.2 + Atmosphere version 1.5.2

**Comment by duckbill007** [comment]
Я не вижу никакого описания ошибки и шагов по ее повторению. Это не форум поддержки. Поддержку ищите в ТГ каналах.

**Comment by ffhome** [comment]
I know I didn't mention the steps to reproduce the problem, but the 551 version really just doesn't connect to MTP, and it displays a regular 'unrecognized USB device'. My friends, including my other switch, can connect to MTP using version 551, indicating that I am in a special situation.

It is puzzling that although my OLED version 551 cannot connect to MTP, there are no issues with using versions 542 and earlier. So I just want to tell you about this situation, which may have some reference significance. Is there any upgrade from version 542 to version 551 that caused the problem.

It's okay, if you don't have the time or can't find the problem, my OLED using DBI 542 version is perfect.
