### ISSUE TITLE
Game Install issue after system reboot

### ISSUE THREAD

**Issue by johnvinsongo** [rashevskyv/dbi#216]
Hi Team,

Could you help me out with a game install issue where its ticket gets erased for no reason after a system reboot.

I have the latest version of DBI and the other mandatory requirements.

**Comment by rashevskyv** [comment]
Fixed in latest version

**Comment by johnvinsongo** [comment]
Thank you rashevskyv. I can confirm that the install issue for newer 16.0.1 games has been fixed.
