### ISSUE TITLE
DBI and exiting

### ISSUE THREAD

**Issue by FlyingBananaTree** [rashevskyv/dbi#22]
@rashevskyv and duckbill - sorry to open an issue again, I was going to comment in this issue https://github.com/rashevskyv/dbi/issues/20 but you closed it and I wasn't sure if you would see my message since it's closed!

I wanted to make a suggestion that instead of having DBI skip hbmenu and return to the homescreen you restore the standard exit behaviour to DBI and instead patch the hbmenu itself with an easy exit option like the following, you could then include this hbmenu nro in the kefir custom firmware pack: https://github.com/HookedBehemoth/nx-hbmenu/commit/6183fed25356e34138366179727ca2c61d84b0bd

I understand why you added the hbmenu skip- you install a game with DBI and then it's annoying and slow to get back to the home menu by pressing the home button but you will find that patching hbmenu like this makes it really fast to get back to the home menu by hitting B a few times, not just for DBI but any homebrew.

One of the main uses of DBI is the MTP mode to transfer and adjust files, especially transferring new homebrew nros or files and then immediately going back to hbmenu to use them rather than being returned to the homescreen, which is why I believe it's better to patch hbmenu instead and solve the problem globally. Hopefully you'll consider this solution as I think it's much more elegant personally. Thanks.

**Comment by duckbill007** [comment]
Next release will include DBI.config file with configurable exit among other options.

Patch for hbmenu I think a must have for Kefir

**Comment by FlyingBananaTree** [comment]
> 
> 
> Next release will include DBI.config file with configurable exit among other options.
> 
> Patch for hbmenu I think a must have for Kefir

That sounds perfect, thank you
