### ISSUE TITLE
Installing XCI files through MTP broken?

### ISSUE THREAD

**Issue by Anonymous-senpai** [rashevskyv/dbi#24]
Running Atmosphere 0.18.1 and DBI 253 on firmware 11.0.1, Windows 8.1

Is it no longer possible to install XCI files through MTP? NSP installs continue to work without a problem. XCI files are rejected upon dragging them to the appropriate spot. 
If I'm not mistaken it used to be possible. It's still possible through the dbi backend but that's somewhat less convenient than MTP.

**Comment by duckbill007** [comment]
It never was possible so it can not be broken. Label file in MTP install dir says: "Place NSP and NSZ files here"

**Comment by Anonymous-senpai** [comment]
Huh, is that so.

I guess I was mistaken then.
