### ISSUE TITLE
Suggestion for contents folder drive in DBI's MTP mode

### ISSUE THREAD

**Issue by FlyingBananaTree** [rashevskyv/dbi#25]
Similar to Saves/Album/Installed games would it be possible to add another virtual drive with game identification for the `contents` folder over DBI's MTP responder? This would be really useful to quickly find games for adding/removing LayeredFS mods and/or cheats. 

For example:
`atmosphere/contents/0100000000010000`

In DBI's MTP responder becomes:
`9: Contents/Super Mario Odyssey`
or maybe:
`9: Mods and cheats/Super Mario Odyssey`

**Comment by duckbill007** [comment]
OK, but it will be 10, not 9. 9 is Gamecard

**Comment by rashevskyv** [comment]
Implemented on v258 
`Installed games/%game_name%/Mods & Cheats`
