### ISSUE TITLE
Applet Mode

### ISSUE THREAD

**Issue by pegast73** [rashevskyv/dbi#285]
Is there any difference between running dbi in Applet Mode and in FULL MEMORY? Is FULL MEMORY mode faster for data transfer?
THX.

**Comment by EvilPanda666** [comment]
Good question. It doesn't appear to need the extra memory to function fully.

**Comment by Masamune3210** [comment]
Some features greatly benefit from it though, like file transfer and package installation

**Comment by pegast73** [comment]
> Some features greatly benefit from it though, like file transfer and package installation

So you recommend FULL MEMORY mode when installing packages?

**Comment by Masamune3210** [comment]
Just use full memory by default for homebrew unless specifically told otherwise. Applet mode is, was, and always will be a stopgap fix.

**Comment by pegast73** [comment]
> Just use full memory by default for homebrew unless specifically told otherwise. Applet mode is, was, and always will be a stopgap fix.

I always install packages in Applet Mode only and it has never failed. I just wanted to know if FULL MEMORY mode will speed up the install. If not, there is no reason to use FULL MEMORY mode...

**Comment by mourisso** [comment]
The .nsz files are compressed and while being descompressed stored in RAM… If you got one big file it will return error on applet mode. I intend to do a PR about this.

**Comment by pixeltester** [comment]
Despite not being typical, dbi's developer always said dbi was designed to be used in applet mode actually.

**Comment by mourisso** [comment]
I actually spoke with him on telegram to give this affirmation...

**Comment by grimson73** [comment]
> I actually spoke with him on telegram to give this affirmation...

Interesting, my largest install was 'EA Sports FC 24 [0100BDB01A0E6800][v393216] (20.87 GB).nsz' and it went wel in applet mode only. Not to criticize anyone but simply curious when issues would arise when using DBI in applet mode (the limited mode).

**Comment by rashevskyv** [comment]
DBI is work fine in both modes, but in some cases there can be issues with low memory on NSZ/XCZ unpacking
