### ISSUE TITLE
An error occurred when using ‘Cleanup orphaned files` feature

### ISSUE THREAD

**Issue by pingowin** [rashevskyv/dbi#29]
firmware 12.0.0
atmosphere 0.19.0
dbi 258
![2021041509365500-6E673B692CCAB4448DD9F18F4ECB7015](https://user-images.githubusercontent.com/82554210/114801833-191c2c80-9dcf-11eb-8626-d37ea3b7ce6d.jpg)

**Comment by Masamune3210** [comment]
make sure you are on the latest build of atmosphere, there was a issue that was fixed with getting title information from ncm. not sure if related

**Comment by pingowin** [comment]
upgrade to atmosphere 0.19.1 and the problem solved
