### ISSUE TITLE
Bug in "Tools --> System info --> Atmosphere info"?

### ISSUE THREAD

**Issue by muxi1** [rashevskyv/dbi#290]
Hi,
I noticed that under "Atmosphere info".
Exosphere blank CAL0 --> no
Emummc enabled --> no
Force enable USB 3.0 --> no
although it should say "yes". Is this a bug?

![281069064-83f33a38-de94-45d3-b25a-00695f5e032e](https://github.com/rashevskyv/dbi/assets/39792666/9c0ab247-d041-44c0-b4ee-59b407a5d6e4)

**Comment by rashevskyv** [comment]
Please provide *system_settings.ini*, *usb30_force_enabled* line

пт, 27 жовт. 2023 р., 15:02 користувач muxi1 ***@***.***>
пише:

**Comment by muxi1** [comment]
However, USB 3.0 is enabled in the system_settings.ini. 
usb30_force_enabled = u8!0x1

This setting is also available in exosphere.ini: 
blank_prodinfo_sysmmc=1
blank_prodinfo_emummc=1

And the emuMMC is also enabled (as shown in the picture above with an "E" at the top).
Hence my assumption that there is a bug there.

**Comment by muxi1** [comment]
I also noticed that the feature "A significant increase game installation speed (~40%+) using multi-threading, especially from USB 3.0 to NSZ in title mode" added under version 460 disappeared at some point in the course of later releases and has now levelled off at USB 2.0 and a speed of around 20-25MB/s under version 628. Unfortunately, the excellent "System Info" feature was not yet available at that time to check whether this bug already existed back then.
