### ISSUE TITLE
MTP Responder not working

### ISSUE THREAD

**Issue by MrSigmaa** [rashevskyv/dbi#294]
Hello all,

I have my switch connected to my PC and when I run MTP responder in DBI, my switch does not show up on my PC

**Comment by muxi1** [comment]
MTP Responder works! Check your USB cable.

**Comment by MrSigmaa** [comment]
I’ve purchased a new able from Amazon, that goes from the C port to the switch. Do I need a chord that does from the USB C port to switch? Because I tried that as well but it did not work. How can I check the usb?
________________________________

**Comment by muxi1** [comment]
> How can I check the usb?

You can check the USB port via Hekate's UMS. If no access to the SD card is possible, there is probably a defect! Consequently, no transfer via the MTP responder will work.

**Comment by MrSigmaa** [comment]
> > How can I check the usb?
> 
> You can check the USB cable/port via Hekate's UMS. If no access to the SD card is possible, there is probably a defect! Consequently, no transfer via the MTP responder will work.

The USB Tool is working fine using Hekate. It opens on my computer perfectly.

**Comment by muxi1** [comment]
> The USB Tool is working fine using Hekate. It opens on my computer perfectly.

Then MTP Responder must also work. I can only say that I was able to carry out numerous installations using MTP Responder under version 628 without any problems.

**Comment by MrSigmaa** [comment]
When I choose MTP, my switch says “waiting for dbibackend to be run”
________________________________

**Comment by muxi1** [comment]
The option "Run MTP responder" has nothing to do with DBIbackend.

**Comment by MrSigmaa** [comment]
Why does it say that when chosen?
________________________________

**Comment by mourisso** [comment]
are you on a mac? I think it should requere an android file manager for it to work on mac

**Comment by MrSigmaa** [comment]
No windows
________________________________

**Comment by muxi1** [comment]
Please check whether the required driver is installed! See here:
https://github.com/rashevskyv/dbi/issues/291#issuecomment-1807105725

**Comment by MrSigmaa** [comment]
I installed those but the same message still shows on my switch “waiting for dbibackend to be run”
________________________________

**Comment by rashevskyv** [comment]
So run mtp responder, not dbibackend installer 🙄

нд, 12 лист. 2023 р., 14:39 користувач Sigma ***@***.***>
пише:

**Comment by MrSigmaa** [comment]
I did but that message still shows up.
________________________________

**Comment by rashevskyv** [comment]
It cannot. Prove it with video

нд, 12 лист. 2023 р., 14:54 користувач Sigma ***@***.***>
пише:
