### ISSUE TITLE
DBI MTP SD card operations

### ISSUE THREAD

**Issue by FlyingBananaTree** [rashevskyv/dbi#3]
I have noticed an issue with file management on the same drive via DBI's MTP, perhaps it's possible to change this?

nx-mtp does a simple file move: 
- Connect MTP and open External SD card, move file from folder 1 to folder 2 on SD card and file is moved instantly.

DBI does a copymove and delete: 
- Connect MTP and open External SD card, move file from folder 1 to folder 2, DBI first copies and then sends the file, then finally deletes the original. This process is very slow if it's a large file.

**Comment by rashevskyv** [comment]
DBI's MTP is for installing games at the first place. Implementing of all MTP protocol's functionality is not very important for now
