### ISSUE TITLE
In-app update?

### ISSUE THREAD

**Issue by hippydave** [rashevskyv/dbi#30]
Thanks for the brilliant app. It would be really convenient if DBI could update itself when a new version is available.

**Comment by rashevskyv** [comment]
You can add DBI manually to [AIO Updater ](https://github.com/HamletDuFromage/aio-switch-updater)

**Comment by hippydave** [comment]
> You can add DBI manually to [AIO Updater ](https://github.com/HamletDuFromage/aio-switch-updater)

You can? Thanks for the tip, but I can't see how to do it.

**Comment by OrGoN3** [comment]
> > You can add DBI manually to [AIO Updater ](https://github.com/HamletDuFromage/aio-switch-updater)
> 
> You can? Thanks for the tip, but I can't see how to do it.

As far as I know, there are two ways. The first would be to set up dns redirecting. Set https://raw.githubusercontent.com/HamletDuFromage/nx-links/master/cfw.json to somewhere locally where you can host your own cfw.json. then edit the file to include DBI.

Or, compile DBI yourself and change line 24,
constexpr const char CFW_URL[] =            "https://raw.githubusercontent.com/HamletDuFromage/nx-links/master/cfw.json";

To point to you sd card, /config/aio-switch-updater/cfw.json. don't forget to download the json and edit it to your liking

**Comment by hippydave** [comment]
> > > You can add DBI manually to [AIO Updater ](https://github.com/HamletDuFromage/aio-switch-updater)
> > 
> > 
> > You can? Thanks for the tip, but I can't see how to do it.
> 
> As far as I know, there are two ways. The first would be to set up dns redirecting. Set https://raw.githubusercontent.com/HamletDuFromage/nx-links/master/cfw.json to somewhere locally where you can host your own cfw.json. then edit the file to include DBI.
> 
> Or, compile aio-switch-updater yourself and change line 24,
> 
> > ` constexpr const char CFW_URL[] =            "https://raw.githubusercontent.com/HamletDuFromage/nx-links/master/cfw.json";`
> 
> To point to you sd card, /config/aio-switch-updater/cfw.json. don't forget to download the json and edit it to your liking

Thanks, that's some great suggestions. I've thought about customising AIOU for myself already, but so far I'm using the official release so I get those sweet sweet auto updates
