### ISSUE TITLE
[Question] Installing via MTP

### ISSUE THREAD

**Issue by nceight** [rashevskyv/dbi#300]
Let's say I have ABC folder containing `ABC [Base].nsp` and `ABC [Update].nsp`. I drag-and-drop to `SD Card Install` and it will install the base game and the update. If I recheck inside `Installed games`, I can see the ABC folder containing the base nsp and the update nsp. But, in the root `Installed games`, I can see `ABC [Base+Update].nsp` with the size of combining files inside in ABC folder. 

My question is, does that mean ABC game takes twice it size? For example, the ABC folder (containing base nsp and update nsp), totaling 10 Gb. By right, it should only takes 10 Gb on the SD Card. But since there is merged nsp ( `ABC [Base+Update].nsp`) which size also 10 Gb, does that mean it takes 20 Gb on the SD Card?

**Comment by Eatmoreapples** [comment]
No. It doesn't need extra space. It's just for dumping purposes

**Comment by nceight** [comment]
No sure how it works, but I'm glad it doesn't. Thanks

**Comment by ToxiClay** [comment]
> No sure how it works, but I'm glad it doesn't. Thanks

It's a "phantom" file that DBI tells Windows about -- without too much exaggeration, DBI is telling Windows "Hey, this file exists on me. It's named this and it's that big" -- and so that's what Windows Explorer displays. It doesn't exist, but Windows doesn't really know that.

**Comment by Masamune3210** [comment]
Basically, the system lies to the comptuer and then if the computer asks for the file, the system does the work of creating the file as its being read.

**Comment by ToxiClay** [comment]
> > It's a "phantom" file that DBI tells Windows about -- without too much exaggeration, DBI is telling Windows "Hey, this file exists on me. It's named this and it's that big" -- and so that's what Windows Explorer displays. It doesn't exist, but Windows doesn't really know that.
> 
> What if I copy the "phantom" file to my PC? Does it give merged nsp that can be install game later?

That's exactly what it does, yes; that's its intent.

**Comment by nceight** [comment]
Neat. Thanks for reply.
