### ISSUE TITLE
About the official Chinese language remove

### ISSUE THREAD

**Issue by dorminirko** [rashevskyv/dbi#306]
Hello developers, as a developer, developing software is based on legality and integrity, but at present, you may be helping others do evil. For a period of time, the Chinese version has remained open and transparent. , but now it seems to be hindering the interests of some people. In China, it is very common to sell other people's things for money, so I hope you will think more about removing the official Chinese version and whether you want to continue to help these crazy people. Just make money.

**Comment by knifeow213** [comment]
San Shang Roast Duck is the garbage in the garbage.He can't represent us ordinary players.

**Comment by rashevskyv** [comment]
Зароаз я розумію нарешті чому шановний автор не хоче підтримувати китайську.
