### ISSUE TITLE
Something About Chinese Version

### ISSUE THREAD

**Issue by cby0608** [rashevskyv/dbi#307]
I'm a Chinese gamer and I can read English. Actually, it doesn't matter if there is an English version or not. Thank you very much for providing the Chinese version for Chinese players. But recently I heard that there was a person claiming to be your friend who asked you to stop updating the Chinese version of DBI, and I thought it was very ridiculous that the person took your stuff and sold it to his fans. This is what he calls influence. Please don't listen to this person, let the majority of Chinese players be hurt, and let you be deceived by him. That person's account seems to be (*DUCK*), but I don't remember exactly. I hope you will continue to provide the Chinese version for Chinese players. Finally, I wish long live the friendship between China and Russia.

**Comment by ghsssss** [comment]
Most Chinese users are ordinary players, and there is no need to stop supporting Chinese because of some people's problems.

**Comment by Fanturner** [comment]
Please don't involve political factors here, and you can't hope for the existence of friendship between China and Russia on behalf of the Chinese people - after all, it is a shame for the Chinese to associate with the invaders. What we want to thank and respect is the open source author of DBI, not the authoritarian country behind him.

**Comment by grimson73** [comment]
Sorry for being off topic but just very curious why there are no language packs and therefore only full localized builds of dbi.nro. I find the author very capable and not judging the choice made but just curious of why.

**Comment by rashevskyv** [comment]
STOP FKNG DRAMA please
