### ISSUE TITLE
im willing to take over chinese translation work of DBI and maintain it.

### ISSUE THREAD

**Issue by WE1ZARD** [rashevskyv/dbi#308]
thank you so much for beening able to provide different lang version DBI to help who has poor language skill,
most of our chinese community are appreciate to this and im willing to take over all the chinese translation work if need.

the ex-chinese version translation author (aka 三上烤鸭 ) get mad and claim he will stop all translation job to DBI cause his bilibili account was banned by selling completely free homebrew which is illegal activities in china.

he is trying to show the power to all chinese community that he has "good connections" with dev by stopping chinese version translation and twisted the truth that chinese community is disrespect to all efforts you guys been achived and think he is only one who able to communicate with dev, which is not true,  ridiculous and selfish just for personal revenges.

here is the proof screenshot from his community, he can do whatever he want just for revenge.
![image](https://github.com/rashevskyv/dbi/assets/111175406/53c8b6de-1968-4169-af78-5ff9ef55397b)

here is the proof about selling free homebrews by masa the author of FPSLocker, status monitor etc.
![image](https://github.com/rashevskyv/dbi/assets/111175406/c95ac646-931f-482d-b311-0b2558cd399e)

his discord id: faker_killer
![image](https://github.com/rashevskyv/dbi/assets/111175406/eeaa1607-a844-4cbb-8b17-4d1091f8946b)

here is his BILIBILI homepage: https://space.bilibili.com/679023184 
![image](https://github.com/rashevskyv/dbi/assets/111175406/8806f7d3-b537-48d4-94da-20a0c6dd891a)
you could find the banned mark on top, next to the skull.
该账号封禁中:  this account was banned.
it was about 4.5+k ppl are paying $1/month on bilibili and i dont think you guys are benefit from this for 1 cent.
to my knowledge, this is away much lower than what he does.(cause he got some communities is doing the same shit.)

his github homepage: https://github.com/sskyNS
his dodo channel: https://www.imdodo.com/s/234298 (similar to discord, but chinese version.)

we respect to any author who bring us these possibilty of switch potention but disagree with person who steal free works from others, claim he own it and sell it for profit, and most important is that he threat to the ppl which is kind and doesnt know the truth. this is absultely unacceptable!

**Comment by lpgneg19** [comment]
Back you up.This guy's a clown.

**Comment by robertchengzy** [comment]
免费个几把，偷别人东西拿去卖。什么垃圾玩意。

**Comment by robertzycheng** [comment]
烤鸭是什么辣鸡玩意，偷别人东西拿去卖叫完全免费？就这么点英文，又不是看不懂。rz一个。

**Comment by yingang** [comment]
Back you up too, I can also contribute to the Chinese translation if needed.

dbi is really awesome!

**Comment by SpinTouch** [comment]
Really can't leave dbi translation to this kind of person. This kind of aggressive person who thinks he is very talented but actually uses his unreasonable troubles to achieve spiritual victory cannot be tolerated. Back you up!

**Comment by jocover** [comment]
he just want to sell homebrew software for monery
but his sales page was banned,so he cancel chinaese translation version

**Comment by Dsseed** [comment]
You can't imagine how happy we were when Chinese was added to the previous version!
Hoping to restore the Chinese language, DBI is the most important tool in the Chinese community, and we are all very grateful to its author!

Because a notorious thief has affected the entire Chinese community, please believe that we will always be your loyal supporters!

Forgive me for my poor English, because many people are worried about this and cannot convey our true thoughts to you, so I must speak up!

**Comment by WE1ZARD** [comment]
> 我只能説，誰才是真正的醜惡的人，誰心裏最清楚1.我的社交賬號不就是被你們舉報的嗎？我也不需要過多辯論什麽，全部的工作都有人見證，你也無須請水軍進行人身攻擊與誹謗，毫無意義。 如果你這麽喜歡斷章取義，我相信你你確實可以矇蔽一部分人，但是你終究只是一個小丑~

我没去找你, 你还主动出来找骂了, 
你的什么鬼生意, 我一点都不在乎, 我也没那个功夫关心,
但是你把整个中文社区拉下水, 损害了所有中文社区的人, 我不能接受.

想用你饭圈的把戏来这里献丑, 我劝你还是别自取其辱, 认清你自己的身份!!!

**Comment by sskyNS** [comment]
Don't humiliate yourself. I don't want to say anything. If you or others hadn't repeatedly slandered others and spread rumors to attack others, none of this would have been a problem. Everything will come to light in the end。
不要自取其辱了，我也不想说什么，如果不是你或者其他人多次诋毁别人以及造谣攻击别人，这些都不会是问题。任何事情到最后都是水落石出

**Comment by sskyNS** [comment]
This is my last reply to this issue, the rest you can freely make up has nothing to do with me, hahaha.
这是我最后一个给这个issue的回复，剩余的你自由胡编乱造与我无关，哈哈哈

**Comment by lv323110011** [comment]
三上烤鸭本来就臭名

**Comment by zuoran99** [comment]
A gentleman takes what he wants! Hypocrites and true villains!
君子爱财，取之有道！伪君子、真小人！

**Comment by pewee-live** [comment]
真的丢人现眼;作者已经失去对中国人的信任了

**Comment by 8CBCA403** [comment]
calm down and stop arguing.

**Comment by Aimer4457** [comment]
虽然没有中文并不会影响使用。但是三上烤鸭这种祸害就应该被抵制。

**Comment by duanshui** [comment]
没关系，没中文更健康！建议作者加入更多防止二次售卖的措施

**Comment by duanshui** [comment]
It doesn't matter, no Chinese is healthier! It is suggested that the authors include more measures to prevent secondary sales

**Comment by liaolia333** [comment]
_San Shang Roast Duck is the garbage in the garbage. It is a garbage bug that uses the labor results of others to generate electricity for love and profit. Even because of this kind of dog, foreigners have a bad impression of the Chinese people. For this kind of dog thing, all of us should ban it, whether it is the Chinese internet or the international internet. Let's unite, despise it, ban it, or even flesh it together, You can take a peek at his various information and give him an offline reality, so that vampires, bugs, maggots who suck on the blood of others' labor can completely socialize and die_

**三上烤鸭就是垃圾中的垃圾，使用别人为爱发电的劳动成果进行售卖，以此牟利的垃圾臭虫，甚至因为这种狗，让外国人也对中国人的印象变得很差，对这种狗东西，我们所有人都应该封杀他，不论是中文互联网也好，国际互联网也罢，大家一起团结起来，唾弃他，封杀他，甚至大家一起人肉他，可以扒一扒他的各种信息，给他来个线下真实，让这种吸别人劳动成果血的吸血鬼，臭虫，蛆，彻底社交性死亡吧**

**Comment by knifeow213** [comment]
San Shang Roast Duck is the garbage in the garbage！He can't represent us.

**Comment by mazjack12138** [comment]
Look at these reviews, Check out sskyns's message. so ugly and so arrogant
Many Chinese will not come here to see the truth and be fooled by this clown.

**Comment by maoxuner** [comment]
I felt grateful when chinese version was released. I'm so shameful now.

**Comment by lpgneg19** [comment]
以上的停止吧，这个软件作者是支持三上的，你们就别再说了。这个软件作者眼里，我们才是无理取闹的人。

**Comment by nulllee** [comment]
Interesting, this dude called"sskyNS" has a very poor spoken English skill. Combining what he did and what he said, I can't find knowledge or morality on him. no wonder how wildly arrogant and unreasonable he is.
And according to the picture, he said he's your pal, Mr.rashevskyv. and if he wants, he can order you to delete Chinese translation from your work. So hilarious.

Thank you for your work and hope there are fewer people like this man.

**Comment by lpgneg19** [comment]
作者是支持三上的，并不站在你们这边。所以，也别说了。

**Comment by nulllee** [comment]
> 作者是支持三上的，并不站在你们这边。所以，也别说了。

yeah, and that's why the whole thing is getting more insteresting.
