### ISSUE TITLE
Bind socket to port 5000 failed

### ISSUE THREAD

**Issue by Ludo-draw** [rashevskyv/dbi#316]
When i use the "run FTP server" im getting this error.
Im not doing anything different from before, also the 5000 port is not in use.
Im saw many people with this problem, but cant find a similar issue here, so i opened a new one;

Bind socket to port 5000 failed: Address already in use
FTP server error

Even if i use the QR Code, conect to the switch-dbi-xxxxxxxxx network it shows the same error

**Comment by sashachirico** [comment]
I have this problem too

**Comment by Jrmewam** [comment]
Same here

**Comment by Ludo-draw** [comment]
they abandoned, sad

**Comment by rashevskyv** [comment]
Turn if it remove sys-ftp
