### ISSUE TITLE
Can't launch it.

### ISSUE THREAD

**Issue by almircanella** [rashevskyv/dbi#32]
Both files nro, config in sd:switch/dbi.

When launched, black screen:

'Fatal error when running atmosphere'
program id: 0100(lot of zeros)0000004
error desc: std: abort() called (0xffe)
press power to reboot.

dbi 260;
Firmware: 11.0.1;
atmosphere: 0.18.0

**Comment by duckbill007** [comment]
Fix atributes on your sdcard
