### ISSUE TITLE
Old 527 release makes double the double speed  compared to 656 MTP responder

### ISSUE THREAD

**Issue by osvaldo27r** [rashevskyv/dbi#326]
Hey Dear DBI team!! Hope you're doing well :) 

This is a Switch Lite (that can't connect with USB 3.0 for some reason, but my OLED simply does with the same USB 3 cable) running CFW 17.0.1, Atmosphere 16.2.

The test was conducted using a Samsung EVO Plus 512GB Sdcard. Installing the same game with both DBI releases, but I can't understand what causing this speed discrepancy in between both DBI versions.

DBI 527
 ![image](https://github.com/rashevskyv/dbi/assets/99234462/7d57ec31-e889-4fe3-afd1-d00fce6d963d)

DBI 656
![image](https://github.com/rashevskyv/dbi/assets/99234462/c3ba4b23-7092-4c34-9bc2-78300070189a)

**Comment by rashevskyv** [comment]
Old releases measured speed incorrectly.  Compare installation time on the same game, not numbers on the screen
