### ISSUE TITLE
USB service sometimes is not closed properly.

### ISSUE THREAD

**Issue by masagrator** [rashevskyv/dbi#33]
Sometimes in Applet Mode when connected to PC using MTP Mode if I will exit from homebrew by pressing home button without closing connection first, PC cannot detect Switch anymore until I will restart Switch (this touches whole HOS).

This happens randomly, but already have this issue more than 5x in last 2 weeks.
Don't know if this happens in title replacement mode.

Had this issue on dbi 260 and 253, Atmosphere 0.18.1 and 0.19.1

**Comment by duckbill007** [comment]
Not sure that it is a DBI issue.

Maybe DBI should block Home button while USB is active, what do you think?

**Comment by masagrator** [comment]
It's possible to block home button with hiddbgDeactivateHomeButton.

But better would be to wait until some other people will confirm that this issue is not isolated.
