### ISSUE TITLE
Can not use USB3.0 in DBI

### ISSUE THREAD

**Issue by johnkelvinliu** [rashevskyv/dbi#341]
A brand new switch OLED with DBI 658+firmware 18.0.1, but no USB 3.0 in DBI?
Only usb 2.0.
The USB cable was tested on another switch OLED that it can run USB 3.0. 
How to solve it?

The following entry has been made inside sdmc:/atmosphere/config/system_settings.ini :
[eupld]
; Disable uploading error reports to Nintendo
; upload_enabled = u8!0x0
[usb]
; Enable USB 3.0 superspeed for homebrew
; 0 = USB 3.0 support is system default (usually disabled), 1 = USB 3.0 support is enabled.
usb30_force_enabled = u8!0x1
[ro]
; Control whether RO should ease its validation of NROs.
; (note: this is normally not necessary, and ips patches can be used.)
; ease_nro_restriction = u8!0x1
[lm]
; Control whether lm should log to the SD card.
; Note that this setting does nothing when log manager is not enabled.
; enable_sd_card_logging = u8!0x1
; Control the output directory for SD card logs.
; Note that this setting does nothing when log manager is not enabled/sd card logging is not enabled.
; sd_card_log_output_directory = str!atmosphere/binlogs
; Atmosphere custom settings
[erpt]
; Control whether erpt reports should always be preserved, instead of automatically cleaning periodically.
; disable_automatic_report_cleanup = u8!0x0
[atmosphere]
; Reboot from fatal automatically after some number of milliseconds.
; If field is not present or 0, fatal will wait indefinitely for user input.
; fatal_auto_reboot_interval = u64!0x0
; Make the power menu's "reboot" button reboot to payload.
; Set to "normal" for normal reboot, "rcm" for rcm reboot.
; power_menu_reboot_function = str!payload
; Controls whether dmnt cheats should be toggled on or off by
; default. 1 = toggled on by default, 0 = toggled off by default.
; dmnt_cheats_enabled_by_default = u8!0x1
; Controls whether dmnt should always save cheat toggle state
; for restoration on new game launch. 1 = always save toggles,
; 0 = only save toggles if toggle file exists.
; dmnt_always_save_cheat_toggles = u8!0x0
; Enable writing to BIS partitions for HBL.
; This is probably undesirable for normal usage.
; enable_hbl_bis_write = u8!0x0
; Enable reading the CAL0 partition for HBL.
; This is probably undesirable for normal usage.
; enable_hbl_cal_read = u8!0x0
; Controls whether fs.mitm should redirect save files
; to directories on the sd card.
; 0 = Do not redirect, 1 = Redirect.
; NOTE: EXPERIMENTAL
; If you do not know what you are doing, do not touch this yet.
; fsmitm_redirect_saves_to_sd = u8!0x0
; Controls whether am sees system settings "DebugModeFlag" as
; enabled or disabled.
; 0 = Disabled (not debug mode), 1 = Enabled (debug mode)
; enable_am_debug_mode = u8!0x0
; Controls whether dns.mitm is enabled
; 0 = Disabled, 1 = Enabled
; enable_dns_mitm = u8!0x1
; Controls whether dns.mitm uses the default redirections in addition to
; whatever is specified in the user's hosts file.
; 0 = Disabled (use hosts file contents), 1 = Enabled (use defaults and hosts file contents)
; add_defaults_to_dns_hosts = u8!0x1
; Controls whether dns.mitm logs to the sd card for debugging
; 0 = Disabled, 1 = Enabled
; enable_dns_mitm_debug_log = u8!0x0
; Controls whether htc is enabled
; 0 = Disabled, 1 = Enabled
; enable_htc = u8!0x0
; Controls whether atmosphere's log manager is enabled
; Note that this setting is ignored (and treated as 1) when htc is enabled.
; 0 = Disabled, 1 = Enabled
; enable_log_manager = u8!0x0
; Controls whether the bluetooth pairing database is redirected to the SD card (shared across sysmmc/all emummcs)
; NOTE: On <13.0.0, the database size was 10 instead of 20; booting pre-13.0.0 will truncate the database.
; 0 = Disabled, 1 = Enabled
; enable_external_bluetooth_db = u8!0x0
[hbloader]
; Controls the size of the homebrew heap when running as applet.
; If set to zero, all available applet memory is used as heap.
; The default is zero.
; applet_heap_size = u64!0x0
; Controls the amount of memory to reserve when running as applet
; for usage by other applets. This setting has no effect if
; applet_heap_size is non-zero. The default is 0x8600000.
; applet_heap_reservation_size = u64!0x8600000

**Comment by muxi1** [comment]
The same problem here under AMS 1.7.0 / FW 18.0.1 / DBI 658. USB 3.0 is displayed as enabled in the DBI system info. Installations via the MTP responder are only carried out with USB 2.0. However, I have set USB 3.0 via exosphere.ini.

**Comment by rashevskyv** [comment]
Works fine on kefir

**Comment by johnkelvinliu** [comment]
Is it possible to make it work again without kefir?

**Comment by rashevskyv** [comment]
It is works fine. There in no any exclusive features for kefir. You should check your own armosphere settings

**Comment by RoboFox83** [comment]
I was having the same issue as johnkelvinliu. 

I have two switches both on 18.0.0 on AMS 1.7. Both had usb30_force_enabled = u8!0x1 under system_settings.ini . One connects at 2.0 and the other at 3.0, using the same cable/port on my PC.

While looking at info from DBI the one that was working shows USB 3.0 says no for Force enable USB 3.0 and the one connecting at USB 2.0 says enabled for Forced enable USB 3.0. Which I would expect the opposite results.

After digging further I found the USB 3.0 Switch was booting using a modified fusee.bin with sigpatches. Where the USB 2.0 was using Hekate with fss0 method to boot Atmosphere.  

It seems the fss0 method doesn't obey my system_settings.ini file, even though the info in DBI says it's forced. Using a modified fusee.bin to boot it with my sigpatches appears to enable USB 3.0 for me. Maybe just adding usb3force=1 to fss0 would work, but that setting says if it doesn't exist it should use system_settings.ini.. which according to DBI it is, but it doesn't actually appear to be enabling it.

Hope this helps, I'm pretty new to all this so please excuse that.

**Comment by johnkelvinliu** [comment]
I also find something similar.
An old instruction a few years ago also said the fss0 would disable the settings in micro SD card/atmosphere/config/system_settings.ini.
It states that typing the followings words in hekate_ipl.ini would help in this case:
usb3force=1 
However it did not state clearly where should we type it in the file. 
I tried typing it under [config], nothing happens; 
While typing it under [CFW - emuMMC], DBI can not connect to the computer via USB.
May be I try yours solution later to see if it works.

**Comment by johnkelvinliu** [comment]
Solution of having USB3.0 again: 
1. add below words in microSDcard/atmosphere/config/system_settings.ini :
[usb]
usb30_force_enabled = u8!0x1

2. get a modified fusee 
https://gbatemp.net/threads/sigpatches-for-atmosphere-hekate-fss0-fusee-package3.571543/page-157#post-10389830 
and put it inside microSDcard/bootloader/payloads/

3. launch the modified fusee in hekate>payload>fusee would enable the USB3.0 again.

**Comment by rashevskyv** [comment]
Or use kefir instead. With much more benefits

**Comment by SwimmingTiger** [comment]
For the Hekate configuration with `fss0=atmosphere/package3`, you need to add `usb3force=1` to each boot menu.

This is my `hekate_ipl.ini`:

```
[config]
autoboot=0
autoboot_list=0
bootwait=3
backlight=89
noticker=0
autohosoff=1
autonogc=1
updater2p=1
bootprotect=0

[Stock]
fss0=atmosphere/package3
stock=1
emummc_force_disable=1
usb3force=1

[EMU Online]
fss0=atmosphere/package3
kip1=atmosphere/kips/loader.kip
emupath=emuMMC/RAW1
emummcforce=1
usb3force=1

[EMU Offline]
fss0=atmosphere/package3
kip1=atmosphere/kips/loader.kip
emupath=emuMMC/RAW2
emummcforce=1
cal0blank=1
kip1patch=nosigchk
usb3force=1
```

**Comment by johnkelvinliu** [comment]
Yes, it works, thx.

**Comment by belmer95** [comment]
> Ho avuto lo stesso problema di johnkelvinliu.
> 
> Ho due switch entrambi su 18.0.0 su AMS 1.7. Entrambi avevano usb30_force_enabled = u8!0x1 in system_settings.ini . Uno si collega a 2.0 e l'altro a 3.0, usando lo stesso cavo/porta sul mio PC.
> 
> Esaminando le informazioni da DBI, quello che funzionava mostrava che USB 3.0 diceva no per Forza abilitazione USB 3.0 e quello che si collegava a USB 2.0 diceva abilitato per Forza abilitazione USB 3.0. Da cui mi sarei aspettato risultati opposti.
> 
> Dopo aver scavato ulteriormente, ho scoperto che lo Switch USB 3.0 si avviava usando un fusee.bin modificato con sigpatches. Mentre l'USB 2.0 utilizzava Hekate con metodo fss0 per avviare Atmosphere.
> 
> Sembra che il metodo fss0 non rispetti il ​​mio file system_settings.ini, anche se le informazioni in DBI dicono che è forzato. Usare un fusee.bin modificato per avviarlo con i miei sigpatch sembra abilitare USB 3.0 per me. Forse aggiungere semplicemente usb3force=1 a fss0 funzionerebbe, ma quell'impostazione dice che se non esiste dovrebbe usare system_settings.ini... che secondo DBI è così, ma in realtà non sembra abilitarlo.
> 
> Spero che questo vi sia utile. Sono piuttosto nuovo in tutto questo, quindi scusatemi.

I also have the same problem, can you send me the link to download the modified fusee.bin?
