### ISSUE TITLE
Stuck in "Calculating install size..."

### ISSUE THREAD

**Issue by laleeroy** [rashevskyv/dbi#353]
So Im trying to access my file listing directory using command python -m http.server ports, but when I click some NSP to install, it just stuck in Calculating install size..., when I do it in mobile browser, It gets downloaded no problem.

Someone help please

**Comment by skalg** [comment]
Hello, i was getting the same issue with python simple http server. Switch to apache and it works flawlessly ! 

here's a simple docker-compose.yml for it : 

version: '3'

services:
  apache:
    image: httpd:latest
    ports:
      - "8080:80"
    volumes:
      - /path/to/expose:/usr/local/apache2/htdocs/:ro

**Comment by laleeroy** [comment]
> Hello, i was getting the same issue with python simple http server. Switch to apache and it works flawlessly !
> 
> here's a simple docker-compose.yml for it :
> 
> ```
> version: '3'
> 
> services:
>   apache:
>     image: httpd:latest
>     ports:
>       - "8080:80"
>     volumes:
>       - /path/to/expose:/usr/local/apache2/htdocs/:ro
> ```

Yes I also switch to apache, thanks for the comment anyway
