### ISSUE TITLE
dbibackend.exe is flagged as Ransomware Trojan Wacapew.C!ml by Windows Security

### ISSUE THREAD

**Issue by MultiKoopa** [rashevskyv/dbi#36]
Is this just a false positive? Chrome also used to go ballistic a month ago...

![dbibackendwindowssecurity](https://user-images.githubusercontent.com/30543543/116837333-fabc7c00-ab97-11eb-9f95-6717a0000ea3.png)

EDIT: And now it's listed as a severe Trojan "Zpevdo.B"

![dbibackendwindowssecurity2](https://user-images.githubusercontent.com/30543543/116837469-94842900-ab98-11eb-8d8b-6e55aa51c974.png)

**Comment by MultiKoopa** [comment]
https://www.virustotal.com/gui/file/28d7add93e250b460f27817089bc7cfdd779dc0b086837e9a581d12bc1469eba/detection

Not sure why so many different antiviruses are picking it up as different types of viruses/malware?

**Comment by Masamune3210** [comment]
Almost all of the detections in the VirusTotal page are heuristic, which usually triggers for open source projects and other things that end up with exes that aren't super wide spread. It's just anti-virus being overprotective 99.4% of the time

**Comment by MultiKoopa** [comment]
> Almost all of the detections in the VirusTotal page are heuristic, which usually triggers for open source projects and other things that end up with exes that aren't super wide spread. It's just anti-virus being overprotective 99.4% of the time

and the Windows Defender results I posted?

**Comment by Masamune3210** [comment]
It doesn't specify what it triggered on, only that it is in the PUP category, which usually just means that it doesn't have enough data to trust what the program is doing in the database

**Comment by MultiKoopa** [comment]
so what you're saying is I can trust it and I'm being paranoid? :)

**Comment by Masamune3210** [comment]
Yee

**Comment by MultiKoopa** [comment]
> Yee

ok. Thank you :)

**Comment by rashevskyv** [comment]
backend built with pyinstaller + `libusb-1.0.dll`. It is just python script included all necessary libraries and binaries for standalone launching. If you paranoid about launching `exe`, just install python and use `dbibackend` python script
