### ISSUE TITLE
DBI 678-ru

### ISSUE THREAD

**Issue by R3m0ved** [rashevskyv/dbi#362]
Can you upload the latest DBI version with english translation ? Duckbill released it on forums only in Russian if i'm not mistaken

**Comment by johnloopi** [comment]
+1 for this @rashevskyv, if it's possible.

**Comment by Bossiskeyboard** [comment]
would love to see

**Comment by 123yonghu** [comment]
+1

**Comment by rashevskyv** [comment]
New versions are only being released in Russian. The author does not want to create versions in other languages and has his own reasons for that, which we must respect and be grateful to him for all the work he has done for the entire Nintendo Switch scene.

**Comment by johnloopi** [comment]
> New versions are only being released in Russian. The author does not want to create versions in other languages and has his own reasons for that, which we must respect and be grateful to him for all the work he has done for the entire Nintendo Switch scene.

That is a shame. I can't even find the source code for it, so I can't build nor update it myself, and I have no interest in using it in Russian. Slava Ukraini.

**Comment by R3m0ved** [comment]
"...we must respect and be grateful to him..."
  - Kim Jong-un democracy officer, 2024
