### ISSUE TITLE
German version? Maybe? 

### ISSUE THREAD

**Issue by HeikesFootSlave** [rashevskyv/dbi#375]
Главное меню                               Hauptmenü
============                               =========
Просмотр SD карты                          SD-Karte durchsuchen

Установка через DBIbackend                 Installiere Titel über DBIbackend

Подключение к серверу...                   Verbindung zum Server...

DBILogs                                    DBILogs

Просмотр установленных игр                 Installierte Titel durchsuchen
Инструменты                                Werkzeuge

Просмотр тикетов                           Tickets durchsuchen
Просмотр сохранений                        Spielstände durchsuchen

Запустить МТР соединение                   Starte MTP Verbindung
Запустить FTP_сервер                       Starte FTP Server
Запустить HTТP сервер                      Starte HTTP Server

Журнал активности                          Aktivitäten Log
Настройки DBI                              Konfiguration
Выход                                      Beenden

Code:

Инструменты                                Werkzeuge
===========                                =====
Очистка системы от мусора                  Verwaiste Dateien entfernen
Удаление родительского контроля            Elternkontrolle entfernen
Удаление пользователя...                   Benutzer löschen...
Удаление Wi-Fi профиля...                  Wi-Fi Profil löschen...
Запустить случайную игру                   Zufälliges Spiel starten
Информация системе                         Systeminformationen
Создание фейковой записи о приложении      Erstelle fake Anwendungseingang

Синхронизация времени по NTP               NTP Zeit synchronisieren
Проверка обновлений игр                    Nach Titel Updates suchen
Обновить titleDB                           TitleDB aktualisieren
Убрать фейковые тайтлы в конец списка      Pack alle fake TIDs ans Ende der Liste
Заполнить свободное место на SD нулями     Fülle den freien Speicher der SD-Karte mit Nullen

I think there are many translations missing that I post here for you! 

Don't even know if you would do that!

**Comment by muxi1** [comment]
It would at least be desirable if an English version were to be published again. A German version would be great, but I don't think it will happen, as such a request was made about a year ago.

**Comment by inspectah88** [comment]
There is an up-to-date German version out there:
https://gbatemp.net/threads/new-tinwoo-installer.659872/page-3#post-10487189
But no idea where to find that friend he made it for.
