### ISSUE TITLE
i can help Feature for lang

### ISSUE THREAD

**Issue by Kronos2308** [rashevskyv/dbi#378]
this is not a issue 
i can ofer some help to manage the translations also to auto change from one language to the other  EN and ES
and othe help you need with the proyect
y have free time

**Comment by Kronos2308** [comment]
Where is the source ?

**Comment by rashevskyv** [comment]
Closed source

пн, 21 жовт. 2024 р., 08:39 користувач Kronos2308 ***@***.***>
пише:

**Comment by Kronos2308** [comment]
I see 

No help needed then ?

**Comment by BaamAlex** [comment]
> I see
> 
> No help needed then ?

It is not that they don't need it, but the authors doesn't want a translation or something which is sad because dbi is (for me) the best title installer.

**Comment by Kronos2308** [comment]
Well there's nothing to do then. 
How strange when I first downloaded the dbi (the latest version) it was in English but suddenly it changed to Russian

**Comment by BaamAlex** [comment]
Hopefully it works on future firmwares because I don't want to use any other installer. Otherwise I swap to the russian version and live with that. Its not that hard for me to press just x to install a game via USB.

**Comment by Kronos2308** [comment]
That's true also
