### ISSUE TITLE
DBI 286 - Installed application's page slow to load when large mod is present

### ISSUE THREAD

**Issue by FlyingBananaTree** [rashevskyv/dbi#38]
Bug introduced with DBI 286 - opening an installed application's page with a large LayeredFS mod in place causes it to take 10+ seconds to open the page, on DBI 272 it was instant. 

The mod is 12GB with many files. If I move or rename the titleid folder the page can be opened instantly again.

Edit - Realized that this was due to the new size check for LFS mods. Maybe allowing the size check for LFS mods to be turned off in `dbi.config` would be the solution.

**Comment by duckbill007** [comment]
OK. Seems to be reasonable.

**Comment by FlyingBananaTree** [comment]
> What about app size in app list? It also can cause slow App list opening.

I only get a very small pause there, maybe half a second. I only have 14 games installed at the moment though.

**Comment by FlyingBananaTree** [comment]
Tested the new config option with DBI 300 and works perfectly, thanks!
