### ISSUE TITLE
DE Version possible?

### ISSUE THREAD

**Issue by Heib386** [rashevskyv/dbi#380]
I saw theres a Portuguese version. 
I am curious, will there be a german version possible?
If so i would like to offer my help. 

Thanks for this awesome app.

**Comment by muxi1** [comment]
@rashevskyv could you please ask duckbill if he could provide you with a German version for publication here on your github? I've read that he doesn't release anything himself (except the current version 713 on gbatemp) and distributes different language versions to his friends. Surely you will be one of those friends and obviously the only one making the DBI available to the public.

**Comment by rashevskyv** [comment]
He dont speak with me. Ask him by yourself on 4pda or gbatemp. Or on
telegram @duckbill007

ср, 23 жовт. 2024 р., 15:50 користувач muxi1 ***@***.***>
пише:
