### ISSUE TITLE
 Protection against OLED screen burn-in

### ISSUE THREAD

**Issue by g1nt0** [rashevskyv/dbi#386]
During extended operations (such as MTP), the OLED screen intentionally remains on, which poses a risk of burn-in, especially with static elements like frames, headers, or footers. High brightness, which I often use in games, further increases this risk. For example, when installing multiple games overnight, the screen may remain on without changes:
![image](https://github.com/user-attachments/assets/328b8d18-afc4-45e0-ae3d-60b4a57da91b)

Adding an option to automatically dim the brightness after a set period would help prevent burn-in and eliminate the need for manual adjustments. Thank you!

**Comment by cristante** [comment]
You can turn off screen in configuration.

**Comment by g1nt0** [comment]
Thanks, I’m closing this.
