### ISSUE TITLE
english? 

### ISSUE THREAD

**Issue by lilfmdude** [rashevskyv/dbi#388]
why is there no more English release?

**Comment by InsanePrimate** [comment]
Because the dev no longer want's to support it and since no one is entitled to another's labor (that would be communism) that's that!

**Comment by pegast73** [comment]
> Because the dev no longer want's to support it and since no one is entitled to another's labor (that would be communism) that's that!

Dev is Ukrainian, he hates Russians. So it's not about communism, but there is something else about it. Who knows why they don't want to make English versions...

**Comment by InsanePrimate** [comment]
I said that the feeling of being entitled to another persons labor is a communist thing! I said nothing about the nationality of the dev and i do not care either way! I am only tired of people who think they are entitled to free shit...

**Comment by rashevskyv** [comment]
https://github.com/rashevskyv/dbi/issues/370
