### ISSUE TITLE
Transfer issue with openmtp

### ISSUE THREAD

**Issue by Disinterpreter** [rashevskyv/dbi#39]
I've got a problem with transfer files from Mac to Switch.

When I try to send files through MTP, I've got an error at my DBI
![image](https://user-images.githubusercontent.com/3816155/122902979-a348ba00-d357-11eb-911a-d17e5556d726.png)
Vice versa transfering is ok (from Switch to Mac)

Perhaps, it can be problem on openmtp, so I'll make an issue there and attach the link here.

I'm watching for this issue and ready to test any things.

**Comment by duckbill007** [comment]
You see the issue on the screenshot: PC side send unexpected command.

**Comment by Masamune3210** [comment]
Specifically the client tried to close the connection without sending anything first

**Comment by Disinterpreter** [comment]
> You see the issue on the screenshot: PC side send unexpected command.
> Also, did you tried Android File Trasfer for mac?

I didn't try Android File Trasfer.

Mac said something like "Unlock your Phone" and closing the connection to MTP

**Comment by duckbill007** [comment]
Check your hardware. Android File Transfer is reported as working solution.

**Comment by Disinterpreter** [comment]
> 
> 
> Check your hardware. Android File Transfer is reported as working solution.

indeed, it can be depends on M1 processor lol
