### ISSUE TITLE
How i change it from applet mode to application mode?

### ISSUE THREAD

**Issue by BlackEagleGermany** [rashevskyv/dbi#394]
"DBI can be then be launched in either applet mode (from Album) or application mode (title override), however it is primarily designed to be used in applet mode."

How i can change it from applet mode to application mode ?

thanks.

**Comment by cristante** [comment]
From the Home screen, close any game playing with X.
Press and keep it pressed the R button ( the one on top of the right trigger ZR ) while start a game with the A button.
Instead of the game it starts the HB menu, from there you choose the DBI.
