### ISSUE TITLE
Suggestion for USB HDD installation

### ISSUE THREAD

**Issue by FlyingBananaTree** [rashevskyv/dbi#4]
I hope you don't mind me posting this to issues, suggesting this for DBI as it is replacing fsp-usb: 
https://github.com/DarkMatterCore/libusbhsfs

With this an atmosphere fork/kip will no longer be needed for USB HDD support.

**Comment by rashevskyv** [comment]
Dbi already support this

сб, 21 нояб. 2020 г., 14:34 FlyingBananaTree <notifications@github.com>:

**Comment by FlyingBananaTree** [comment]
DBI supports fsp-usb, this is replacing fsp-usb- "With this an atmosphere fork/kip will no longer be needed for USB HDD support"

**Comment by duckbill007** [comment]
libusbhsfs license is not compatible with DBI.

**Comment by FlyingBananaTree** [comment]
> 
> 
> libusbhsfs license is not compatible with DBI.

I see, maybe a custom solution will be needed in the future as fsp-usb development will end I believe.

**Comment by FlyingBananaTree** [comment]
> libusbhsfs license is not compatible with DBI.

Looks like it has been changed "Relicensed library under the ISC License"

**Comment by rashevskyv** [comment]
Implemented :)

**Comment by FlyingBananaTree** [comment]
> Implemented :)

Great work!
