### ISSUE TITLE
DBi 286 is faster than version 300 and 306 in reading external hardrive

### ISSUE THREAD

**Issue by ginkuji** [rashevskyv/dbi#41]
I have an external hardrive with more than 200+ nsp inside. The version 286 reads it faster than 306. Maybe something in the update starting from 300 made the reading the hardrives slower.

**Comment by Eusino** [comment]
The same thing happens to me, now it is extremely slow to open a folder with many files in versions> 286 (in 286 it is instantaneous regardless of the number of files it contains)

**Comment by rashevskyv** [comment]
https://github.com/rashevskyv/dbi/issues/38

**Comment by FlyingBananaTree** [comment]
> 
> 
> #38

@rashevskyv this issue would need a seperate config entry from duckbill since the one he added was for LFS mod check size only.

**Comment by rashevskyv** [comment]
Oh, external drive, my bad

ср, 7 июл. 2021 г., 09:13 FlyingBananaTree ***@***.***>:

**Comment by duckbill007** [comment]
libusbhsfs provides only stdio interface for file operations. 
so, for receiving file size it needs to call stat for each file.
on microsd native FS calls are used and file sizes are received as batch duringg directory scan.

To speed up new option will be added.

**Comment by rashevskyv** [comment]
https://github.com/rashevskyv/dbi/releases/tag/307

**Comment by Eusino** [comment]
Perfect! now it is instant again with the new option
