### ISSUE TITLE
ApacheHTTP url

### ISSUE THREAD

**Issue by proconsule** [rashevskyv/dbi#44]
I am developing a php script for NSP indexing.
My script will print a directory listing page if a $_GET parameter is in the url
example: index.php?DBI=true

i tried but DBI refuse to show the server probably because isn't a path of the server like /switch/
Is possible to implement an url like this in DBI so it can be used like this

Tanks

**Comment by duckbill007** [comment]
DBI suppports apache servers with directory listing enbled.
Also it supports other servers if they has the same behaviour.

I have no idea how php scripting works but if you want that DBI supports your script , then make it produce the same output as apache servers with directory listing.

**Comment by duckbill007** [comment]
All I can do is to remove check that initial URL ends with '/' but all output should be the same as Apache's directory listing.

**Comment by proconsule** [comment]
> 
> 
> All I can do is to remove check that initial URL ends with '/' but all output should be the same as Apache's directory listing.

This will be great, i think this is the only thing that prevents my script to work with DBI since my script will output same as apache directory listing,
Tanks for your reply

**Comment by duckbill007** [comment]
Right now you can just add / to end of your url and check

**Comment by proconsule** [comment]
nice suggestion, i will try this and let you know if it works.
Tanks and sorry for the misunderstanding on gbatemp post

**Comment by NaruZosa** [comment]
Please remove the '/' check, it caused a lot of confusion for me during setup, as I would never usually end the url with a slash and had no idea why the remote locations weren't showing.
