### ISSUE TITLE
Allow installations dock usb connected to pc

### ISSUE THREAD

**Issue by pitrako** [rashevskyv/dbi#45]
Can you allow It to install directly through the dock connected to pc?, I tried with an usb hdd, It works, but you have to transfer the files to It first and you lose time. Can you do It?

**Comment by duckbill007** [comment]
Dock accepts connection only USB slave devices. On windows youu can do nothing. On linux with custom kernel and some specific hardware you can switch USB port to slave mode.

**Comment by pitrako** [comment]
Ok, I understand, closing issue.
