### ISSUE TITLE
Unable to force language

### ISSUE THREAD

**Issue by Mr-Q** [rashevskyv/dbi#46]
Hi,

My system language is Dutch but I would like to use English (e.g. for The Legend of Zelda).
When I go into the list of Installed Apps, I can select the game and then the option to 'Force Language' in the sub-menu for each item (base, updates & DLC).

The system shows 'System default' and a list of other languages (e.g. American English, Britisch English). However, when I select one of them nothing happens. I still see 'Forced language' set to 'System default' in the overview screen of the game, and also it shows all the supported language (e.g. RU, EN, FR, DE, ES IT, NL, JA, KO, ZH).

This is also happens with 'Super Mario Maker 2' (which only has a base application).

I tried many keys but it looks to me I should select it using the 'A-button' which is confirm in all of the menu, but it doesn't work (the list of languages just disappears)

I am using DBI version 312 with system version 12.0.3 and Atmosphere 0.19.5 and sigpatches.

**Comment by FlyingBananaTree** [comment]
It sounds like you don't have a contents folder and DBI doesn't create one if it doesn't exist (atmosphere doesn't include a contents folder by default anymore so probably would be good if DBI did that)

Create a contents folder at `sdmc:/atmosphere/contents` and DBI will then be able to write the config.ini file. Also you only need to activate the force language for the base game and not the update and all DLC, all of them write the same file.

**Comment by Mr-Q** [comment]
This indeed is the issue! The folder was not there so I created it. Then after changing the language it was indeed directly visible in the summary. The game starts with the other language :)

Would be great for other users facing the same issue if the directory is created by DBI or an error message is shown.
