### ISSUE TITLE
MTP does not work in versions after 175

### ISSUE THREAD

**Issue by ZUIcat** [rashevskyv/dbi#5]
I found that the version after 175 added "Checks the cable connection before starting the MTP".
But MTP does not work in versions after 175 in my computer.
It always stays at the countdown and then ends, and the computer does not respond.

**Comment by rashevskyv** [comment]
Works fine for me. Try to see if there is all drivers installed in device manager or try to use another USB-cord

**Comment by ZUIcat** [comment]
> Works fine for me. Try to see if there is all drivers installed in device manager or try to use another USB-cord

Before version 175 and its version, the driver was displayed normally, but after version 175, the driver manager displayed "Cannot find the device driver".

Is there any option or configuration to turn off cable connection check? I think turning on MTP without checking will solve my problem.

**Comment by rashevskyv** [comment]
IDK, try to reinstall MTP drivers or something. All must works fine

**Comment by rashevskyv** [comment]
https://github.com/rashevskyv/dbi/releases/tag/197
Please try this version

**Comment by ZUIcat** [comment]
> https://github.com/rashevskyv/dbi/releases/tag/197
> Please try this version

Perfect! Version 197 works very well. It directly opened the MTP, and my computer identify it quickly.
