### ISSUE TITLE
Incompatible with Atmosphere 0.19.5

### ISSUE THREAD

**Issue by tdevineni** [rashevskyv/dbi#51]
I tried to use DBI with Atmosphere 19.5 and it simply crashes OS. The NRO shows an exclamation mark in hbmenu. I really need this app to fix data storage issues on my console. Is there anyway to make DBI work with current CFW ? Or is there a pending release to fix compatibility with current AMS?

**Comment by rashevskyv** [comment]
Reinstall app properly. Try to fix atributes.
! means that nro is broken

пт, 13 авг. 2021 г., 00:02 tdevineni ***@***.***>:
