### ISSUE TITLE
Feature request: FTP server + Network installing via FTP

### ISSUE THREAD

**Issue by BlackRabbit22** [rashevskyv/dbi#55]
The ability to launch an FTP server and also have the ability to perform installations by dropping a file/files into a folder and perform network installations (similar to how MTP installations work but via FTP).

**Comment by duckbill007** [comment]
HTTPS is way more reliable and secure.

**Comment by BlackRabbit22** [comment]
@duckbill007 FTP is way simpler to use, and FTP can be implemented to use a login.
TLS for title installations is over kill. 
Also I don't think 90% of the DBI user base is setting up a webserver in order to use network installations.

Please reconsider this feature request since it will benefit users greatly.

**Thank you.**

**Comment by wangrui1573** [comment]
apache or ngnix is too hard for me，ftp is simply
