### ISSUE TITLE
I follow the Tutorials try to make USB3.0 work.

### ISSUE THREAD

**Issue by Lather0519** [rashevskyv/dbi#57]
Я следил за руководством и обнаружил, что в папке атмосферы \ config нет файла с именем "system_settings.ini", поэтому я создал его на рабочем столе, ввел в него требуемый контент и переместил его в соответствующее место. Ситуация пока удовлетворительная.Я создал эту задачу в основном для того, чтобы понять, возможно ли в будущем создавать невозможные ошибки?

**Comment by duckbill007** [comment]
This shit not related to DBI
