### ISSUE TITLE
MTP transfer is not working in Atmosphere 1.0

### ISSUE THREAD

**Issue by madskyer** [rashevskyv/dbi#58]
MTP usb file transfer is not working properly in the new atm version: https://github.com/Atmosphere-NX/Atmosphere/releases/tag/1.0.0

It starts, but most of times it fails (smaller files have more chance to transfer).

Thanks for all the work.

**Comment by rashevskyv** [comment]
Works fine for me

вс, 12 сент. 2021 г., 09:01 madskyer ***@***.***>:

**Comment by madskyer** [comment]
Sorry, i changed the USB port after your comment and it seems to work fine.

Thanks.
