### ISSUE TITLE
Error occur when uploading >4GB xci

### ISSUE THREAD

**Issue by HY-Leung** [rashevskyv/dbi#6]
It is fine, as older version I used (1.51)

 after I upgrade to the latest one, this kind of error appear:

 When my switch connect to PC with a usb cable, and upload a 6GB xci (any files over 4GB) with the MTP function, it success without warning. However when I exit and go to the album (in order to load the game), it must crash!

Then, I take out the micro-sd card from my switch and insert to PC with card reader 
the micro-sd did not contain the XCI file, but it contain a folder name xxxxxxxx.xci, the folder inside it has files of 4GB and remainding 2GB.

So, I think the program has missed a process of joining the files (or some issue that without report errors)

I use SXOS. and dbi.nro
and this problem appear every time I upload file over 4GB

Thanks

**Comment by rashevskyv** [comment]
No, all works that is expected. Try with another game. Maybe exactly that game you have tried with is currupted or not supported with SXOS

**Comment by FlyingBananaTree** [comment]
That's the expected behaviour. In order to support FAT32 with 4GB max filesize limit, DBI splits the file and places the parts in an archived folder so the OS can read it as a single file.

**Comment by HY-Leung** [comment]
Strange, every time I upload the big XCI files with MTP to the first drive (different games titles), it leave this error that crash the system without anything reported fail in DBI or windows. 

Then I need to take out the MicroSD from switch and put into the card reader, delete the job folder and transmits the same XCI file to MicroSD on PC. After put back to switch, it works. So, I'm sure the xci file (I made by NSC builder) is not corrupted and works fine.

Do you want me make a video to show this?

**Comment by rashevskyv** [comment]
Yes, please. Video will be helpful

**Comment by HY-Leung** [comment]
oh, Finally, I found out what the problem is 

Since I use Mac OS sometimes, it leaves two hidden folder on my SD card: .fseventsd and .Spotlight-V100
it makes the dbi occur this kind of error.

After I deleted that two hidden folder, everything alright now.

**Comment by JrRadiant** [comment]
> Mac OS

Please _do not_ use Mac OS with Switch, for god's sake.  :pray:

**Comment by HY-Leung** [comment]
> > Mac OS
> 
> Please _do not_ use Mac OS with Switch, for god's sake. 🙏

Sorry I've only mac devices at home, just used the VM of windows 10 from my MAC. (parallel desktop) it work fine.

However, I want to say that why the DBI mtp responder only support type-c connection, not support the USB 3.0 interface from the stand.

**Comment by HY-Leung** [comment]
Crash again tonight after copying another 18.8GB XCI to microSD via DBI.nro v1.95 MTP 

This time I found totally 3 folders that with a .xci name in the SDcard. (including two of them can run into SXOS normally before)
 i.e. All files that over 4GB upload via DBI will become folders. And it is normal before another file uploaded tonight. It crash now. 
I've check that there are no any hidden files (starting with dot) in the SDcard. But it crashs !
