### ISSUE TITLE
Support for new storage format

### ISSUE THREAD

**Issue by BlackRabbit22** [rashevskyv/dbi#61]
Titles such as **Lost in Random**, **Last Stop**, and **NMH3** cannot be installed properly due to the new storage format they have.

**Comment by duckbill007** [comment]
It is not an installer, but a dumper issue. There is no new storage format, but different crypto. Installer just copies data from dump to console. From my point of view dumps of that titles has incorrect/incomplete tickets.

**Comment by BlackRabbit22** [comment]
> It is not an installer, but a dumper issue. There is no new storage format, but different crypto. Installer just copies data from dump to console. From my point of view dumps of that titles has incorrect/incomplete tickets.
@duckbill007 
**NMH3** has been dumped by different people, its not an incorrect or incomplete ticket. The same goes for the other titles I mentioned. Someone even tried to dump it via DBI, and it was still having issues. 

Installing via DBI shows that the ticket is also okay, however the installation still is broken and the title cannot launch. Try it out for yourself. 

Either the DBI dumper is broken, or the installer is broken.

**Comment by duckbill007** [comment]
OK. Fixed installing in 330.

**Comment by BlackRabbit22** [comment]
@duckbill007 thank you.

**Comment by R-YaTian** [comment]
> OK. Fixed installing in 330.

Hello, duckbill. Could you tell me how it works? I tried to add installing sparse titles support for AtmoXL-Titel-Installer, but still not working. Could you please help me with it? Thank you very much.
