### ISSUE TITLE
An error occurred when using “Cleanup orphaned files” feature

### ISSUE THREAD

**Issue by blackzinn01** [rashevskyv/dbi#62]
**Firmware**: 12.1.0
**Atmosphere**: 1.0.0
**Emunand**: Hidden Partition (Hekate).
**DBI**: 330.

![2021091716235800](https://user-images.githubusercontent.com/89793165/133843821-c53a7eec-5935-4c45-85b7-43768e7acb5a.jpg)

I don't know if it's a DBI problem or an emunand problem. I've checked the integrity of all of my applications and it's okay. How can I solve it?

**Comment by duckbill007** [comment]
This men's that you have a file that is not belongs to any registered application, but system can not delete it. Possible cause is filesystem corruption. Check it on PC using chkdsk
