### ISSUE TITLE
New storage format support 

### ISSUE THREAD

**Issue by impeeza** [rashevskyv/dbi#63]
Titles such as Lost in Random, Last Stop, and NMH3 cannot be installed properly due to the new storage format they have.

On AtmoXL installer they solve with:
https://github.com/R-YaTian/AtmoXL-Titel-Installer/commit/a5765075adc31d7c213d7e8b9cb86bb19577d0ee
Adding the code:

`contentMetaHeader.attributes = packagedContentMetaHeader.attributes; // Sparse Titles use 0x04 not 0x0`

**Comment by duckbill007** [comment]
It is implemented a long time ago.

**Comment by impeeza** [comment]
yey, thanks a lot.   kudos.
