### ISSUE TITLE
Windows 11

### ISSUE THREAD

**Issue by tsukina22** [rashevskyv/dbi#64]
Hello, i don't know if is only with me, but on Windows 11, the switch folder that used to show up on windows 10, to install games, doesn't appear anymore, like, looks like is connected, on DBI on switch is saying is connected, but no Switch folder, and i even try to put hidden folder to show up, and didn't. 
![IMG_20211007_162045_086](https://user-images.githubusercontent.com/75396328/136450461-cd6cf615-4231-4961-81c8-1bf41724ebe4.jpg)

**Comment by rashevskyv** [comment]
Never tested upon windows 11.

чт, 7 окт. 2021 г., 22:33 tsukina22 ***@***.***>:

**Comment by impeeza** [comment]
You must go to "devices" (or whatever is callerd on Portuguese) there you can navigate the mtp devices. Is an new annoying issue of Windows 11

**Comment by Luka9kw** [comment]
How did you solve it? I have the same problem...

**Comment by tsukina22** [comment]
> How did you solve it? I have the same problem...

I didn't solve it, no matter what i did didn't work, i even tried to return to Windows 10 without formatting but the timing was already over to do that, so i had to format my PC and put Windows 10 again, i don't think after that i want to go to Windows 11 again, lol

**Comment by impeeza** [comment]
if you did hide the MTP devices on explorer, you need enable,
press start button, and select the settings wheel:
![image](https://user-images.githubusercontent.com/41979604/165811638-7e93c7d3-b4fd-4843-a623-7256d6efc609.png)

thend go to bluetooth and devices:
![image](https://user-images.githubusercontent.com/41979604/165811694-d660c095-44fe-44b1-bff3-81130c911499.png)

select "view more devices"
![image](https://user-images.githubusercontent.com/41979604/165811759-af91b104-22de-4c7b-a73c-21382bac46db.png)

scroll until you find "Switch":
![image](https://user-images.githubusercontent.com/41979604/165811863-7612a2ce-13e6-4af9-bf09-db0e8120c29d.png)

if you found it all is working but if not, you need to manually install the windows driver for MTP, some installations of windows 11 do not have it for default:
right click start menu orb and select "Device Manager":
![image](https://user-images.githubusercontent.com/41979604/165813873-6fe69042-a5fd-4aae-9fa0-d640de8db42f.png)

On action menu, select add legacy hardware
![image](https://user-images.githubusercontent.com/41979604/165813922-0da03871-09bb-49f6-bf88-10520d688b8f.png)

on the wizard select next
![image](https://user-images.githubusercontent.com/41979604/165813949-e1008516-86f5-4686-9271-403bd93105ea.png)

![image](https://user-images.githubusercontent.com/41979604/165814052-6b107d1a-30e7-4d46-b644-609d42df750e.png)

![image](https://user-images.githubusercontent.com/41979604/165814074-75c33954-d5da-4fb4-8ad3-ad2ffa4fd720.png)

![image](https://user-images.githubusercontent.com/41979604/165814107-49914ebb-576f-47dd-a979-bbb43d4450c0.png)


![image](https://user-images.githubusercontent.com/41979604/165814132-8b980954-21f5-4621-8134-9233679b2b29.png)


![image](https://user-images.githubusercontent.com/41979604/165814171-3d1fc0db-b63a-4820-a6d2-da0073256d42.png)


![image](https://user-images.githubusercontent.com/41979604/165814201-e2480faf-3e72-4382-8f50-7b9c57235c64.png)


The error "Device cannot start" it's normal, when you plug the switch on  MTP mode again it will show on explorer

**Comment by tsukina22** [comment]
> if you did hide the MTP devices on explorer, you need enable, press start button, and select the settings wheel: ![image](https://user-images.githubusercontent.com/41979604/165811638-7e93c7d3-b4fd-4843-a623-7256d6efc609.png)
> 
> thend go to bluetooth and devices: ![image](https://user-images.githubusercontent.com/41979604/165811694-d660c095-44fe-44b1-bff3-81130c911499.png)
> 
> select "view more devices" ![image](https://user-images.githubusercontent.com/41979604/165811759-af91b104-22de-4c7b-a73c-21382bac46db.png)
> 
> scroll until you find "Switch": ![image](https://user-images.githubusercontent.com/41979604/165811863-7612a2ce-13e6-4af9-bf09-db0e8120c29d.png)
> 
> if you found it all is working but if not, you need to manually install the windows driver for MTP, some installations of windows 11 do not have it for default: right click start menu orb and select "Device Manager": ![image](https://user-images.githubusercontent.com/41979604/165813873-6fe69042-a5fd-4aae-9fa0-d640de8db42f.png)
> 
> On action menu, select add legacy hardware ![image](https://user-images.githubusercontent.com/41979604/165813922-0da03871-09bb-49f6-bf88-10520d688b8f.png)
> 
> on the wizard select next ![image](https://user-images.githubusercontent.com/41979604/165813949-e1008516-86f5-4686-9271-403bd93105ea.png)
> 
> ![image](https://user-images.githubusercontent.com/41979604/165814052-6b107d1a-30e7-4d46-b644-609d42df750e.png)
> 
> ![image](https://user-images.githubusercontent.com/41979604/165814074-75c33954-d5da-4fb4-8ad3-ad2ffa4fd720.png)
> 
> ![image](https://user-images.githubusercontent.com/41979604/165814107-49914ebb-576f-47dd-a979-bbb43d4450c0.png)
> 
> ![image](https://user-images.githubusercontent.com/41979604/165814132-8b980954-21f5-4621-8134-9233679b2b29.png)
> 
> ![image](https://user-images.githubusercontent.com/41979604/165814171-3d1fc0db-b63a-4820-a6d2-da0073256d42.png)
> 
> ![image](https://user-images.githubusercontent.com/41979604/165814201-e2480faf-3e72-4382-8f50-7b9c57235c64.png)
> 
> The error "Device cannot start" it's normal, when you plug the switch on MTP mode again it will show on explorer

Unfortunately, for me, this didn't work either, was saying that the MTP failed to be transferred from Win 10 to Win 11, in Windows 10 such error never appeared, besides there is a lot of games that Win 11 doesn't support, so i had to go back anyway.

**Comment by tsukina22** [comment]
> This solved my problem completely. The Switch was showing up as a device, but it was unplugging and plugging in nonstop. I tested it with another cable and miraculously it fixed it. I believe it is some incompatibility between the switch and windows with the speed of the cable I was using. Thanks for your help!!

Luck for you that worked, i tried that too, but didn't worked either, my error was pretty deep than this, i found Win 11 a lot more beautiful than Win 10, but Win 11 doesn't support a lot of program and games that i have, so i found better to go back to Win 10.

**Comment by impeeza** [comment]
this instructions could help you:
https://thegeekpage.com/fix-mtp-not-working-in-windows-10/

**Comment by rashevskyv** [comment]
Cannot reproduce on Windows 11

**Comment by Luka9kw** [comment]
works fine here
