### ISSUE TITLE
The menu Browse saves display username abnormally

### ISSUE THREAD

**Issue by ZUIcat** [rashevskyv/dbi#67]
When a enter the menu **Browse saves**, it shows my username on the left.
But all of them shows my first username, even if it is a different user’s savedata.
I switched my user order in the system settings and returned to DBI, and it did show the first user name I set.

DBI version: 330
OS version: 10.2.0|AMS 1.1.1|E

**Comment by duckbill007** [comment]
I have absolutely no idea what are you talking about
