### ISSUE TITLE
Create Brazilian Portuguese Language in "Force Language Options"

### ISSUE THREAD

**Issue by FelipeFares** [rashevskyv/dbi#68]
Hi, besides anything, I appreciate the high-value application that is DBI xD!

Please, could you put the option Brazilian Portuguese in "Force Language Options"

![WhatsApp Image 2021-10-25 at 09 18 05](https://user-images.githubusercontent.com/17763747/138699268-da09c7d1-e318-4200-98fd-0be6d4f30d09.jpeg)

**Comment by FelipeFares** [comment]
> The list of supported languages is taken from the game itself

I Really don't know It... I thought that it was a Parameters... It was Nintendo's fault So xD!!

**Comment by duckbill007** [comment]
Atmosphere's language override does not support "Brazilian Portuguese":
https://github.com/Atmosphere-NX/Atmosphere/blob/master/libraries/libstratosphere/include/stratosphere/settings/settings_types.hpp

**Comment by FelipeFares** [comment]
> Atmosphere's language override does not support "Brazilian Portuguese":
> https://github.com/Atmosphere-NX/Atmosphere/blob/master/libraries/libstratosphere/include/stratosphere/settings/settings_types.hpp

Man!! I'm glad that you answered me!!

**Comment by FelipeFares** [comment]
> Atmosphere's language override does not support "Brazilian Portuguese":
> https://github.com/Atmosphere-NX/Atmosphere/blob/master/libraries/libstratosphere/include/stratosphere/settings/settings_types.hpp

Duck, I think the Portuguese language could suppress my need... But I can't understand why this doesn't show on DBI xD!

![image](https://user-images.githubusercontent.com/17763747/140115012-d88e2055-9667-4630-bd73-7260fd3567d9.png)

**Comment by duckbill007** [comment]
DBI do support Portuguese:
```
    const std::array<std::tuple<std::string, std::string, std::string>, 16> Languages =
        {{
            {"", "System default", ""},
            {"en-US", "American English", "usa"},
            {"en-GB", "British English", "eur"},
            {"ja", "Japanese", "jpn"},
            {"fr", "French", "eur"},
            {"de", "German", "eur"},
            {"es-419", "Latin American Spanish", "usa"},
            {"es", "Spanish", "eur"},
            {"it", "Italian", "eur"},
            {"nl", "Dutch", "eur"},
            {"fr-CA", "Canadian French", "usa"},
            {"pt", "Portuguese", "eur"},
            {"ru", "Russian", "eur"},
            {"ko", "Korean", "kor"},
            {"zh-Hant", "Traditional Chinese", "twn"},
            {"zh-Hans", "Simplified Chinese", "chn"}
        }};
```

If it is not shown thaen game not suport it.
