### ISSUE TITLE
Feedback and bug for USB HDD installation (libusbhsfs)

### ISSUE THREAD

**Issue by FlyingBananaTree** [rashevskyv/dbi#7]
Some feedback for the new USB HDD installation feature (Atmosphere 0.15.0 **without** fsp-usb running, Firmware 10.2.0):

- Games install correctly but after exiting DBI you can get an error
- After installing any game from USB HDD if you exit and open DBI again you will get a black screen and you are unable to open DBI again until you reboot the Switch
- The installation speed seems slower, around 33% - 50% of what it was with fsp-usb (I used the same exFAT USB HDD to test)

**Comment by rashevskyv** [comment]
How do you launch DBI? Applet (albums) or title (game) mod?

**Comment by rashevskyv** [comment]
And did you tests installation with the same game to the same place?

**Comment by FlyingBananaTree** [comment]
> 
> 
> How do you launch DBI? Applet (albums) or title (game) mod?

I tested both and it was the same for both.

> 
> 
> And did you tests installation with the same game to the same place?

I tested two games both in AUTO mode.

**Comment by rashevskyv** [comment]
Try with latest version please. It built with newest version of libusbhsfs

**Comment by FlyingBananaTree** [comment]
> 
> 
> Try with latest version please. It built with newest version of libusbhsfs

Tested (firmware 11.0.0 and atmosphere 0.16.0 second prerelease):

- Speed is a lot faster, looks the same as fsp-usb or maybe a bit faster

- There are still some errors after installing games from USB drive. For example this is what happened:

1. Install game from USB0, the game installs correctly
2. Exit DBI and receive error (Nintendo error, asking to share or do not share error report)
3. Open DBI again, it works
4. Install another game from USB0
5. Exit DBI, no error
6. Open DBI, black screen

**Comment by FlyingBananaTree** [comment]
DBI 202: USB drive not detected at all in DBI

**Comment by duckbill007** [comment]
Since 202 libusbhsfs is opt-in: to use it create /switch/dbi.libusbhsfs flag file.

**Comment by duckbill007** [comment]
Also, make sure you are using dbi in applet mode.

**Comment by FlyingBananaTree** [comment]
> 
> 
> Since 202 libusbhsfs is opt-in: to use it create /switch/dbi.libusbhsfs flag file.

Ok thanks, is that for hiding the option while it's under development?

Anyway I just tried it and USB0 is not appearing with DBI.nro + dbi.libusbhsfs flag file in either /switch/ or /switch/DBI/ (I usually use folder)

It appears fine in 201.

**Comment by rashevskyv** [comment]
Try with new 204 version

**Comment by FlyingBananaTree** [comment]
> 
> 
> Try with new 204 version

The flag works now.

Atmosphere 0.16.0 prerelease 2, DBI 204, tested firmware 10.2.0 and 11.0.0, both same result.

Application mode: install, exit, open DBI, result- black screen

Applet mode: install, exit, open DBI, result- Atmosphere error https://gist.github.com/FlyingBananaTree/21675bfb212ecaf95e66b3b4a6dbf501

**Comment by duckbill007** [comment]
Did you tried the same scenario with libusbhsfs example application?

Black bg is intentional. DBI not designed to be run in application mode.

**Comment by FlyingBananaTree** [comment]
> 
> 
> Did you tried the same scenario with libusbhsfs example application?
> 
> Black bg is intentional. DBI not designed to be run in application mode.

I checked, it seems that the example application can also trigger this bug. I'll open an issue there.

By the way I've never had an issue with DBI in application mode, unless you mean it can specifically cause issues with libusbhsfs.

**Comment by FlyingBananaTree** [comment]
@duckbill007 It was a libusbhsfs issue.

Should be fixed in: https://github.com/DarkMatterCore/libusbhsfs/commit/ae8663d1244b50ec49c99d9196ce4b54b42ea740

**Comment by FlyingBananaTree** [comment]
Confirmed fixed in DBI 206, thanks!
