### ISSUE TITLE
cant open dbi backend

### ISSUE THREAD

**Issue by butawsky** [rashevskyv/dbi#70]
"failed to execute script_pyi_usb"  i get this error opening the dbi backend.exe how do i solve this error?

**Comment by rashevskyv** [comment]
Try to turn off your antivirus

**Comment by butawsky** [comment]
i dont have any anti virus installed on my pc...

**Comment by Masamune3210** [comment]
If you are on windows, yes you do. Defender is built in

**Comment by butawsky** [comment]
will try it again tom..btw thankyou very much for making this very useful app..
