### ISSUE TITLE
ExFat support with MTP protocol

### ISSUE THREAD

**Issue by Lokagan** [rashevskyv/dbi#71]
Retriving file with MTP on a Exfat filesystem fail if filesize is > 4GB. 
It only send the last slice of a 4GB hash process.

**Comment by rashevskyv** [comment]
Y u need transfer smth so big to sd? Just curious

**Comment by Lokagan** [comment]
Backuping installed NSP…

**Comment by duckbill007** [comment]
When you moving backup of installed nsp via MTP it does not matter is it exfat or fat32.

Just tried move Witcher3 nsp via MTP. No issue at all. Check your environment.

**Comment by Lokagan** [comment]
Just tried another mtp client. Yep it is working.
I confirm my issue is Debian related.
