### ISSUE TITLE
Reset required version - does'nt remove the "a software update is required" nag

### ISSUE THREAD

**Issue by popy2k14** [rashevskyv/dbi#72]
When i use "Reset required version " (ith or without Atmosphere debug mode). DBI always says "OK" and displays the last update version. Game could be launched when pressing "Start Software", sadly the nag is'nt gone.

My AMS Setup is up to date on 13.1.0 + AMS 1.2.4 + hekate 5.6.5 + DBI 336.

Any hint's what i am doing wrong?

Read some posts from you on gbatemp, where you speak from modifing "8000000000000045" save.
An hint's on this? Can this be deleted without bricking my switch?

thx

**Comment by duckbill007** [comment]
This works only on kefir cfw.

**Comment by popy2k14** [comment]
Thanks for the hint.
Want to stay on atmosphere official release.

Some questions:
1. Does this need patching some source code files in atmosphere to work?
2. Or can this be manually be done? (ex. edit some files with hakdiskmount)
3. Can i jump my emummc to kefir just for reseting the versions and then back to official atmosphere and will the nag be gone

**Comment by rashevskyv** [comment]
As i remember, you should enable debug for Atmosphere. Check or use kefir's
config for Atmosphere

чт, 11 нояб. 2021 г., 09:08 popy2k14 ***@***.***>:

**Comment by popy2k14** [comment]
Sorry not to mention it, already enabled debug for atmosphere without success.
Will look into the kefir's config file for atmosphere.

**Comment by duckbill007** [comment]
Reset required does not mean nag absence. It will allow you run game. Nothing more.

**Comment by popy2k14** [comment]
ok thx to clear things up.
Is there a way to prevent/remove the nag also? (ex.: editing "8000000000000045")

**Comment by popy2k14** [comment]
@duckbill007 
Found your post on gbatemp: https://gbatemp.net/threads/is-there-a-way-to-remove-the-a-software-update-is-required-nag-without-updating.568139/post-9234642

Does this also work on newer FW version like 13+?
Is it possible to integrate into DBI?

**Comment by duckbill007** [comment]
Yes. It works. Yes, its possible but with restart since its a system save. No, I wont do this because of restart.

**Comment by popy2k14** [comment]
That is an often requested feature when you search in various places.
This would be an killer DBI feature :-)

No chance of getting it? Also if after changing things an reboot is required)

**Comment by Ammako** [comment]
I'm not sure hex editing the save data really works, or not anymore at least. Whenever I tried it, the system just crashes on loading any game afterwards.

Don't delete the save, HOS won't boot with it not present and it will not regenerate them on its own.

Best imo is to just extract the blank save data from a freshly formatted emmc (make an emummc or something), and overwrite the files in your main emmc with the blank save data. This wipes all traces of game updates from your system and gets rid of all game update nags in one go.

**Comment by popy2k14** [comment]
thx for the hint!

Tried the following, without luck:

- Flashed 13.1.0 with daybreak and factory reset ticked in emummc -> switch stuck @ reboot
- Reseted working emummc with maintaince mode, copy the ..0045 save to the other emummc -> nag is still present

This solved it for me:
- Reseted working emummc with maintaince mode
- Set this up without going online
- > NAG is gone but i had to reinstall everything!

**Comment by Ammako** [comment]
Forgot to mention, you need 8000000000000180 for version list. 8000000000000045 is only for required version list.

**Comment by popy2k14** [comment]
Thanks for the hint, that could work :-)
Can't try it because already factory reseted all.

**Comment by popy2k14** [comment]
@duckbill007 Any chance of getting such a feature for the mentioned files 8000000000000180 & 8000000000000045.
