### ISSUE TITLE
potential DBIBackend python script improvement

### ISSUE THREAD

**Issue by rdmrocha** [rashevskyv/dbi#73]
It seems like after a random update on my mac, the python script and the USB subsystem are not behaving as they should. The device reset command looks like it's running asynchronously on the macs or at the very least, the device isn't fully ready after the reset is issued.

I found that injecting and artificial delay between reset and set_configuration on line 155 solves the issue 100% of the times in my MBP 2018 model (not sure about potentially slower machines).

```python
...
dev.reset()

print('Waiting for switch reset...')
time.sleep(1)

dev.set_configuration()
cfg = dev.get_active_configuration()
...
```

Hope it helps

**Comment by rashevskyv** [comment]
Can you make PR?

**Comment by FlyingBananaTree** [comment]
@rashevskyv There isn't actually anywhere to PR to yet, can I suggest that you add `dbibackend.py` and `dbi.config` to the repository's files section (alongside `README.md` and `README_END.md`)?

That will allow people to follow changes more easily and make them open to pull requests.

**Comment by rashevskyv** [comment]
Oh, crap, my fault, sorry. I will add backend to sources with this fix.


пн, 22 нояб. 2021 г., 03:08 FlyingBananaTree ***@***.***>:

**Comment by rashevskyv** [comment]
Fixed in next release. Thank you!
