### ISSUE TITLE
Install title from USB not detecting cable connected

### ISSUE THREAD

**Issue by emersonjr** [rashevskyv/dbi#74]
Simply as that, I'm starting the backend server on my PC, then it waits for switch...
From switch i go to DBI, install title from USB, the message requesting cable Type-C appears, i connect the cable but nothing else happens. 

I hear the positive sound of PC detecting something got connected but that's just it, DBI doesn't recognized it's really connected. MTP method works fine btw. I followed what's in #52  but it didn't work.
Could anybody give some help?

**Comment by ancabung** [comment]
Hi I have the same problem. 
So after a while trying to figure what's wrong, I find in the device manager shows it's connected as DBI with a "!" mark saying drivers are not installed. Install the tinfoildriver doesn't automatically detected the driver for DBI, so I have to right-click on it and browsing the tinfoildriver to manually install it. Unplug replug the cable and everything works fine now. Hope this will help you fix it. Sorry my English suck.

**Comment by xXS4ALLx** [comment]
Why use the backend sever? it is not needed, just use the MTP option instead, on your PC, your SWITCH will have it's own drive. To install games just drag and drop into the appropriate folder.

**Comment by MadaoDev** [comment]
> Hi I have the same problem. So after a while trying to figure what's wrong, I find in the device manager shows it's connected as DBI with a "!" mark saying drivers are not installed. Install the tinfoildriver doesn't automatically detected the driver for DBI, so I have to right-click on it, update driver and browsing the tinfoildriver to manually install it. Unplug replug the cable and everything works fine now. Hope this will help you fix it. Sorry my English suck.

thank you so much, this helped me a lot cuz i was trying to transfer a 4gb file that doesnt work with the format i have on the SD card.
