### ISSUE TITLE
Laggy Power Menu

### ISSUE THREAD

**Issue by BlackRabbit22** [rashevskyv/dbi#75]
When launching MTP responder, and then connecting to a PC and then exiting out of the homebrew launcher, and finally holding the power button to get to the power menu, the power menu starts lagging and all of qlaunch gets extremely slow. This is gone after a reboot.
This occurs only with the latest version of DBI. DBI 336 works fine.
This was tested on two devices, one running windows and the other running linux.
I also tested with different USB cables.
The Switch is running a clean version of atmosphere, so no sysmodules, or anything else. 
This issue occurs in both applet mode, and full ram mode.

These are the specifications of the device:
* FW: 13.1.0
* CFW: Atmosphere 1.2.4
* Device Type: Mariko

**Comment by duckbill007** [comment]
How do you exit from DBI?

**Comment by BlackRabbit22** [comment]
@duckbill007 by pressing the home button if I'm in applet mode, and in full ram mode, I press +.

**Comment by BlackRabbit22** [comment]
@duckbill007 by pressing the home button if I'm in applet mode, and in full ram mode, I press +.

**Comment by duckbill007** [comment]
Use exit and all be fine.
