### ISSUE TITLE
Hardrive not recognized

### ISSUE THREAD

**Issue by ginkuji** [rashevskyv/dbi#8]
I am using the latest build 195.
Running atmosphere 15 on 10.2 firmware
I am also running DBI on NSP forwarder.
I have three hardrives all formated to exfat

Two of my hardrives are using an enclosure (1 tera western digital, 2 tera toshiba). These are working well with DBI.
The third hardrive is a western digital passport external hardrive. DBI simply hangs after I tried accessing the files inside. I already tried reformating it but still, it won't read. The light indicator for the hardrive stays still.

Note:
I have tried all three hardrives with tinfoil and they all work. I do not know what causes the error for DBI. 

Thank you for your hard work updating DBI. I hope I am able to give good feedback that can help the program's improvement.

**Comment by rashevskyv** [comment]
USB support on DBI uses https://github.com/DarkMatterCore/libusbhsfs library. Try to make issue there, or wright issue on gbatemp's related thread. 
Try https://github.com/rashevskyv/dbi/releases/tag/191 and [ams_mitm.zip](https://github.com/rashevskyv/dbi/files/5641044/ams_mitm.zip) (put it in `atmoaphere\kips`, works only for atmosphere 0.15). If all yours HDDs will works fine, there is definitely libusbhsfs  issue

**Comment by ginkuji** [comment]
Thank you for redirecting me where to post my report. 
The problem is now fixed by the developer.
Source: https://github.com/DarkMatterCore/libusbhsfs/issues/7

**Comment by rashevskyv** [comment]
Oh! That's cool! Let's wait until duckbill make new build without this issue! Thanx for reporting
