### ISSUE TITLE
Apache HTTP server speed

### ISSUE THREAD

**Issue by Adamados** [rashevskyv/dbi#80]
When i install/configure the HTTP Server (Apache) i had a issue with download/installation speed.

If i download via my Browser from PC i download any file from http server at max network speed (90 MB/s) but when i install/download from nintendo switch it is running at 5-8 MB/s

Even i follow one guide [from 4pda forum](https://4pda.to/forum/index.php?showtopic=939714&st=9640#entry110250717) that suggest to put this settings
```
EnableMMAP off
EnableSendfile off
```
still didnt see any improvement.

Did i need to configure from DBI anything else that i am missing (because from web browser my download speed is maximum) ?

**Comment by rashevskyv** [comment]
Use 5ghz wifi

пт, 17 дек. 2021 г., 00:44 Adamados ***@***.***>:

**Comment by duckbill007** [comment]
Or better - use ethernet conection on your dock. It is easy to achieve 35+ MB/s

**Comment by Adamados** [comment]
> Use 5ghz wifi 

Just connected to 5ghz and yes, saw an improvement up to 11 MB/s
Will continue to investigate

**Comment by Adamados** [comment]
I just figure out that the problem is in Nintendo switch OS (atmosphere? NS Horizon OS? Switch WiFI?)

Install the Awoo Installer and use the [ns-usbloader](https://github.com/developersu/ns-usbloader) and from there select the NET option and enter the Switch IP and when send the game the transfer speed was aprox same (to be honest was worse, via apache max speed was 11 MB/s and via Awoo Installer - ns-usbloader was 8 MB/s

So my apache server work fine and DBI settings are fine also
