### ISSUE TITLE
Cleanup orphaned files - select what to clean

### ISSUE THREAD

**Issue by mspykerez** [rashevskyv/dbi#81]
Is it possible to give a report of what the 'Cleanup orphaned files' feature finds and before it cleans anything let us select what we actually want it to clean if anything.

**Comment by rashevskyv** [comment]
There will be no files you can use.

пн, 20 дек. 2021 г., 13:52 mspykerez ***@***.***>:

**Comment by mspykerez** [comment]
Still, I would very much like to have a report of what exactly I am cleaning before I agree to do the actual cleaning.

**Comment by mspykerez** [comment]
Well I'm not asking for detailed info on every single file found that can be cleaned but judging from the description of what the feature is supposed to do ''cleans up unnecessary game files, files from interrupted/failed game installations, officially downloaded firmware updates and all unused game tickets'', providing a report separating the files into these categories, like 'files from failed game installations', 'firmware updates', 'unused game tickets', etc with the ability to select the categories we wish to clean should suffice.

**Comment by duckbill007** [comment]
Absolutely unnecessary. You do not like it, then you not using it. Or write your own cleaner.

**Comment by mspykerez** [comment]
ok but at least can we have a confirmation after we click the thing, I mean missclicks sometimes happen...

**Comment by rashevskyv** [comment]
This option makes no problem to yuor system even if you missclick to it.
But yes, conformation for it and for deletion would be fine imo

пн, 20 дек. 2021 г., 14:52 mspykerez ***@***.***>:

**Comment by mspykerez** [comment]
Sorry to bother again..
my reluctance with it is because of this issue https://github.com/rashevskyv/dbi/issues/10
I like my XCI and the dream would be that one day DBI would support XCI mounting by its own so I can play games directly from an external disk.

Speaking of XCI, can you tell if DBI supports installing 'Super XCI' (an XCI file that also contains updates or DLCs all put together in the same file) ? If so, what is the installing behavior? Does it install the game plus updates and DLC all at once or can you pick and choose to install only the game, update or DLCs separately?

Also is there any advantages using the dbibackend over the MTP responder? Like in terms of reliability and install speeds?

**Comment by rashevskyv** [comment]
DBI and atmosphere will never support mounting games. DBI is app for installing games and it cannot mount games without atmosphere support mounting itself. Atmosphere will **never** support mounting couse it's author will never support piracy. 

DBI support super XCI and will install all it is components without giving a choice of what to install

**Comment by mspykerez** [comment]
>DBI support super XCI and will install all it is components without giving a choice of what to install
What if the same update or DLCs or even newer ones are already installed, what is the behavior them?

Asking because coming from SX OS to Atmosphere I already have a bunch of updates and DLCs installed for games that I only run by mounting the XCI, so only the base game is not installed. If I were to use DBI to install the superXCI of these games will any currently installed updates/DLCs be overwritten by those on the superXCI or will DBI ignore them if the same or newer version is detected?

Also if I were to just install a regular non-super XCI file, will the updates and DLCs that I already have installed still work? or I have to completely uninstall everything and reinstall from scratch?

note: I already have the entry on my Switch for every game that I mounted with XCI, some of which also have updates/DLCs installed separately via NSP, the entry is just sitting there on the Switch game menu waiting for the XCI to be mounted so I wonder too if I need to perform some sort of uninstall of these entries first before using DBI to install the XCI or if DBI will just overwrite them or make a new entry despite the titleID being the same.

>is there any advantages using the dbibackend over the MTP responder? Like in terms of reliability and install speeds?
