### ISSUE TITLE
No backend available error

### ISSUE THREAD

**Issue by scalp42** [rashevskyv/dbi#83]
Hi there

Running into an issue with the USB connection. Switch seems to be fine with `waiting for dbibackend to be run` but locally running into issues:

```
$❯ python3 dbibackend

DEPRECATION WARNING: The system version of Tk is deprecated and may be removed in a future release. Please don't rely on it. Set TK_SILENCE_DEPRECATION=1 to suppress this warning.
{'blabla.nsz': PosixPath('/Users/scalp/blabla.nsz')}
Exception in thread Thread-1 (start_server):
Traceback (most recent call last):
  File "/Users/scalp/.asdf/installs/python/3.10.1/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/Users/scalp/.asdf/installs/python/3.10.1/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/scalp/dbibackend", line 172, in start_server
    connect_to_switch()
  File "/Users/scalp/dbibackend", line 149, in connect_to_switch
    dev = usb.core.find(idVendor=0x057E, idProduct=0x3000)
  File "/Users/scalp/.asdf/installs/python/3.10.1/lib/python3.10/site-packages/usb/core.py", line 1309, in find
    raise NoBackendError('No backend available')
usb.core.NoBackendError: No backend available
```

DBI version: `350`
Atmosphere `1.2.5` (fw `13.2.0`).
Python: `3.10.1`
MacOS: `12.1` (**M1 silicon**) 

PS: MTP responder won't work on MacOS

Thanks in advance for any pointer! 🙏

**Comment by duckbill007** [comment]
It is macos on m1 issue. Sorry, that setup not supported. Use windows PC.

**Comment by scalp42** [comment]
Closing as it's not supported.

**Comment by lekseven** [comment]
Is it still not supported? I get the same issue on M1 Pro.

**Comment by duckbill007** [comment]
Mac and especially non Intel will never be supported.

**Comment by lekseven** [comment]
For future readers.
A working solution for M1 Macs:
DB Installer in MTP Responder Mode on Switch + Android File Transfer on M1.

**Comment by JagandeepBrar** [comment]
I also ran into the same issue but after running `brew install libusb` I had to ensure I was using the brew installed version of Python3 and pip3 (you can run `where python3` and `where pip3` to get the path, it's likely in `/opt/homebrew/bin/*`).

Then run `<path to homebrew pip3> install pyusb` and `<path to homebrew python3> ./dbibackend`.

My machine: M2 Macbook Air

**Comment by ProgrammingW** [comment]
> I also ran into the same issue but after running `brew install python-tk libusb` I had to ensure I was using the brew installed version of Python3 and pip3 (you can run `where python3` and `where pip3` to get the path, it's likely in `/opt/homebrew/bin/*`).
> 
> Then run `<path to homebrew pip3> install pyusb` and `<path to homebrew python3> ./dbibackend`.
> 
> My machine: M2 Macbook Air

Hey, could you please elaborate on that? Im having the same problem
