### ISSUE TITLE
macOS install guide

### ISSUE THREAD

**Issue by richardstefun** [rashevskyv/dbi#86]
Turns out it runs just fine on macOS too.

1) xcode-select --install
2) brew install python-tk
3) pip3 install pyusb
4) python3 dbibackend

**Comment by bandithedoge** [comment]
Have you figured out the MTP Responder on macOS?

**Comment by duckbill007** [comment]
On non M1 use Android file transfer. On M1 not supported.

**Comment by bandithedoge** [comment]
Thanks. It appears support for MTP in macOS is an issue in general.
