### ISSUE TITLE
DBI 197 feedback

### ISSUE THREAD

**Issue by FlyingBananaTree** [rashevskyv/dbi#9]
- USB (MTP or dbibackend) does not work on firmware 11.0.0 and atmosphere 0.16.0 (second prerelease) and causes crash, it works on firmware 10.2.0 and atmosphere 0.16.0
- DBI menu has laggy input response (fine in DBI 195)

**Comment by ThePsycrow** [comment]
I just tested this program for the first time via USB and also got an error/crash screen.  Is it supposed to work on version 11?
I put the nro file in the correct folder on my SD card to be able to run it from the homebrew menu, wasn't sure what to do with "dbibackend" (the one with no extension) but tried it both in and out of that folder, same error.  There was also an exe included but it gets a red malware warning from Windows before trying to open it so I didn't.

**Comment by rashevskyv** [comment]
@ThePsycrow please open another issue and use newest version of program. Add screenshots with error. 
> I put the nro file in the correct folder 
What folder. We do not know what folder is correct in your opinion 

> but tried it both in and out of that folder, same error
What means "tried"? What folders?

**Comment by rashevskyv** [comment]
FlyingBananaTree 
1. Fixed in 201. Please check it out and try install smth from external USB on 11th. Thank you for you help!
2. Yep, but it is no big problem imo.

**Comment by ThePsycrow** [comment]
Oh you fixed it with the update from an hour ago -- that one wasn't showing up yet for me when I downloaded -- thanks!

**Comment by FlyingBananaTree** [comment]
> 
> 
> FlyingBananaTree
> 
>     1. Fixed in 201. Please check it out and try install smth from external USB on 11th. Thank you for you help!
> 
>     2. Yep, but it is no big problem imo.

No problem, it all looks fine on 11.0.0 now!

Not a big problem with the menu lag but would be nice if it could be snappy again ;)
