### ISSUE TITLE
List missing updates and DLC

### ISSUE THREAD

**Issue by mspykerez** [rashevskyv/dbi#93]
Is it possible to list missing updates/DLCs for installed games by matching against the titledb that is regularly updated here https://github.com/blawar/titledb ?

So even if DBI doesn't scan any update files it will still say that an update is missing if it's on the titledb therefore we would know that it exists somewhere if we wish to look for it.

**Comment by JrRadiant** [comment]
You can use [NX-Update-Checker](https://github.com/16BitWonder/NX-Update-Checker) for this.

**Comment by mspykerez** [comment]
Still would be nice to have it integrated into dbi by default.
The amount of little things that nowadays we rely to get the Switch running is piling up... I'd prefer to have as many features possible consolidated.

**Comment by duckbill007** [comment]
Done in 366

**Comment by mspykerez** [comment]
> Done in 366

Excuse my asking but where is 366?
Is it being released on another place?
I can only see it here on GitHub up to v358

**Comment by rashevskyv** [comment]
Maybe it will be released soon

**Comment by duckbill007** [comment]
Currently it is not stable and only in beta testing.
