### ISSUE TITLE
Backup up saves to my PC since I had to reformat Switch. But cannot restore saves now? Save files "can not be created"

### ISSUE THREAD

**Issue by thrik** [rashevskyv/dbi#94]
I believe I'm doing it right, but it is not letting me put them back on my Switch :(

**Comment by rashevskyv** [comment]
Provide mire info or close issue

**Comment by thrik** [comment]
When I try to restore the saves, that is the error I get. For instance,
"Save for Zelda Breath of the Wild can not be created".

That is all the info that is provided in the app.

**Comment by duckbill007** [comment]
У меня всё работает. Если не работает - пиши точно что делаешь и как повторить.

**Comment by thrik** [comment]
Sorry, I'm not sure what more information I can possibly provide.

Backing up the saves was fine. They're on my PC.

When I open DBI on my Switch, run MTP Responder, and then try to copy the saves that I backed up (currently on my PC) over to 7: Saves it provides that error on DBI.

**Comment by duckbill007** [comment]
Ещё раз: какую конкретно папку в какую конкретно папку на устройстве копируешь?

**Comment by thrik** [comment]
The folders within Saves, of course.

Respectively, the folders from Installed Games/Uninstalled Games that include the game saves.

I am observing the simple hierarchy of these paths when I copy them from my PC to my Switch.

**Comment by duckbill007** [comment]
Понятно. Нормально, однозначно ответить на вопрос ты не хочешь. Всё работает как должно, ищи проблему у себя.

**Comment by rashevskyv** [comment]
Check if usernames are the same. And provide screenshots if you want to help.

**Comment by thrik** [comment]
Thank you rashevskyv for actually providing something for me to go on. The usernames are the same, I checked that as well. Do you mean a screenshot of the error text on the Switch? If so I will post this. Thanks

**Comment by thrik** [comment]
Here are some pictures. 

I noticed I did have better luck with titles that were installed (after I had to reformat). But, I could not transfer any saves for titles that were not already installed. I'm not sure if this is by design or not, I did not see any documentation on your Github relating to this. 

<img width="611" alt="Screenshot 2022-03-28 114816" src="https://user-images.githubusercontent.com/326814/160440966-56337bf1-1fa0-4d92-9947-98b8aa0119ff.png">

![2022032811502300-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/326814/160440980-26c846e4-bf30-430d-8f8a-2bbb86507630.jpg)

**Comment by rashevskyv** [comment]
Only for installed.

пн, 28 мар. 2022 г., 19:11 thrik ***@***.***>:

**Comment by thrik** [comment]
Okay, that makes sense, I'm sure it has something to do with how the Switch handles creating save file spaces. Thank you :)

**Comment by FlyingBananaTree** [comment]
> Yeah for future reference, save archives can only be created by the game, so you have to run them at least once to create the archive. Then you can do whatever you want

No, DBI can initialize saves either over MTP or within the homebrew itself.

**Comment by Masamune3210** [comment]
Why not do it automatically if the user is trying to restore a backed up save and the archive doesn't already exist then? Maybe with a notice or prompt to catch edge cases?

**Comment by FlyingBananaTree** [comment]
> Why not do it automatically if the user is trying to restore a backed up save and the archive doesn't already exist then? Maybe with a notice or prompt to catch edge cases?

It's drag and drop over MTP. rashevskyv already explained why it didn't work for this user so no particular need to chime in after the issue is closed and give bad info if you don't know how the homebrew works.
