### ISSUE TITLE
Unable to open images on Switch with Windows Photo Viewer

### ISSUE THREAD

**Issue by ToxiClay** [rashevskyv/dbi#96]
Disclosure: I admit, this is an edge case.

When browsing the Album using DBI's MTP Responder mode, I am unable to open photos directly off of the Switch.

# Steps

1. Enable MTP Responder and connect to PC.
2. Wait for MTP synchronization.
3. Access Album drive.
4. Find a photo.
5. Double-click photo.
6. Observe DBI's information log displaying "Sendfile error -5"
7. Windows Photo Viewer hangs, blaming COM Surrogate for the failure.

# Screenshots
![image](https://user-images.githubusercontent.com/13796683/163701574-e6bcd46f-5179-4761-8093-a9c9abf7a428.png)
![2022041701145000-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/13796683/163701576-9c2e21e8-9f9e-4449-ae6e-87e2ace38465.jpg)

**Comment by duckbill007** [comment]
Sorry, no Windows support provided. Works perfect in Linux.

**Comment by lowburger** [comment]
Problem in your system... this all work completely fine on windows, I use a lot.
