### ISSUE TITLE
Unable to back up certain files from Atmosphere through MTP Responder

### ISSUE THREAD

**Issue by ToxiClay** [rashevskyv/dbi#97]
I'm currently exploring using DBI as an alternate method for backing up my Switch's SD card, and I'm running into a problem. There are two specific files, namely `<SERIAL>_BISKEYS.bin` and `<SERIAL>_PRODINFO.bin` that DBI appears to choke on when asked to transfer, claiming that the resource is already in use. Windows gives an "Unspecified error," and file transmission stops.

I'm not entirely sure why these files are actively being written to by Atmosphere; I suspect that perhaps Atmosphere holds the file handles open so they can't be tampered with, maybe? Strangely, they *are* deletable through DBI, just not transferrable. These backups generate automatically on AMS bootup, though, so deleting them to prepare for the backup is, while a possible solution, somewhat tedious.

Is there a potential solution, or is this just a weird quirk that I will have to work around?

# Screenshot
![2022041701581800-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/13796683/163702753-5a4695f6-1a9f-4307-a7df-32a0d8112e70.jpg)

**Comment by ToxiClay** [comment]
I'm also unable to transfer `\Nintendo\save\8000000000000124`, which is reportedly "the [NCM module](https://switchbrew.org/wiki/NCM_services) save describing what contents are installed to the SD card."

**Comment by Masamune3210** [comment]
Not a DBI issue, Atmosphere disallows access to files it deems important or required for the system to function to keep people from accidentally getting themselves stuck and to keep the environment sane so it doesnt crash. Basically, if its in the atmosphere folder, you likely wont be able to touch it while booted. 

As for the NCM save, since the system mounts it at boot and its locked, you likely wont be able to back it up either

**Comment by ToxiClay** [comment]
The weird thing is, I'm able to *delete* them just fine, and I can transfer (and delete) everything else just fine.

**Comment by Masamune3210** [comment]
Not sure why you are able to delete them as that should be rejected as well, but as long as you havent corrupted anything or messed with your prodinfo they will just be regenerated on next boot anyway so it doesnt matter much

**Comment by Masamune3210** [comment]
Makes me wonder if Atmosphere is just lying and saying they are deleted when they really arent?

**Comment by ToxiClay** [comment]
> Makes me wonder if Atmosphere is just lying and saying they are deleted when they really arent?

Only one way to find out.

Hmmmm. You might be right:

1. Opened MTP Responder
2. Deleted the automatic_backups folder
3. Closed MTP Responder
4. Re-opened MTP Responder
5. Folder is back.

So either Atmosphere is in fact lying to DBI, or Atmosphere is regenerating the backups constantly. But the weird thing is, if Atmosphere can lie to DBI and say "Oh yeah I can delete those for you boss, no worries," why can't it copy them?
![2022041704274301-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/13796683/163706885-b8d68ce0-4609-4a37-9ae9-504b4f8a6e97.jpg)

**Comment by Masamune3210** [comment]
Copying involves opening the file for reading, which is disallowed. Deleting doesn't afaik. Also, MTP isn't exactly the smartest protocol ever. I've had the same magical disappearing folder trick happen on phones and a folder that was disallowed

**Comment by lowburger** [comment]
That's normal atmosphere protections...
