### ISSUE TITLE
DBI HTTP speeds is not utilizing full speed

### ISSUE THREAD

**Issue by vegedb** [rashevskyv/dbi#99]
For testing the same **exact** file & HTTP server is used. **_Same exact environment._**

To monitor the speed, I'm using windows counter,
![image](https://user-images.githubusercontent.com/72070424/165730113-b64bdb75-4cff-46a8-a3b5-52bc5ebdb460.png)

DBI = 7MB/s max speed
Tinfoil = 20MB/s max speed

I prefer using DBI, so hope you could fix this issue.

**Comment by rashevskyv** [comment]
Thats true. Maybe sometime it will be improved
